Repository depromeet/14th-team5-iOS, pull requests merged in 2023-12, with the labels that each got.

#15 feat: KingFisher, FSCalendar 의존성 추가
  App.xcworkspace/contents.xcworkspacedata
  App.xcworkspace/xcshareddata/xcschemes/App-Workspace.xcscheme
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/ModuleType+Templates.swift
  Tuist/ProjectDescriptionHelpers/Package+Templates.swift
Labels: ⚒️ SETTING, 🥰 건우

#20 feat: Tuist WidgetExtensions 추가 및 Bundle Id 수정
  14th-team5-iOS/App/Project.swift
  14th-team5-iOS/App/WidgetExtension/Resources/empty.txt
  14th-team5-iOS/App/WidgetExtension/Sources/WidgetExtension.swift
  14th-team5-iOS/App/WidgetExtension/Sources/WidgetExtensionBundle.swift
  App.xcworkspace/contents.xcworkspacedata
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Modular+Templates.swift
  Tuist/ProjectDescriptionHelpers/ModuleType+Templates.swift
  Tuist/ProjectDescriptionHelpers/Package+Templates.swift
  Tuist/ProjectDescriptionHelpers/Products+Templates.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ProjectDescriptionHelpers/ResourceFileElements+Templates.swift
  Tuist/ProjectDescriptionHelpers/SourceFilesList+Templates.swift
  Workspace.swift
  pippi.xcworkspace/.tuist-generated
  pippi.xcworkspace/contents.xcworkspacedata
  pippi.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  pippi.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  pippi.xcworkspace/xcshareddata/xcschemes/pippi-Workspace.xcscheme
Labels: ⚒️ SETTING, 🦊 도현

#22 feat: 위젯 개발을 위한 폴더 구조 및 기본작업 셋팅
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyWidget.swift
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyWidgetEntry.swift
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyWidgetTimelineProvider.swift
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyWidgetView.swift
  14th-team5-iOS/App/WidgetExtension/Sources/WidgetExtension.swift
  14th-team5-iOS/App/WidgetExtension/Sources/WidgetExtensionBundle.swift
Labels: ✨ FEATURE, 🐭 건희

#32 Feat/#24 kakao login 셋팅 및 개발
  .DS_Store
  14th-team5-iOS/App/Project.swift
  14th-team5-iOS/App/Sources/Application/AppDelegate.swift
  14th-team5-iOS/Data/Sources/Service/KakaoSignInHelper.swift
  14th-team5-iOS/Domain/Sources/Account/AccountSignIn/AccountSignInHelperType.swift
Labels: ⚒️ SETTING, ✨ FEATURE, 🐭 건희

#33 feat: 페밀리뷰 추가
  14th-team5-iOS/App/Sources/Presentation/Main/Model/SectionOfFamily.swift
  14th-team5-iOS/App/Sources/Presentation/Main/Reactor/MainViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Main/Reactor/ProfileReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Main/String/MainStringLiterals.swift
  14th-team5-iOS/App/Sources/Presentation/Main/ViewControllers/MainViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Main/Views/FamilyCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Main/Views/ProfileView.swift
  14th-team5-iOS/App/Sources/Presentation/ViewController.swift
Labels: ✨ FEATURE, 🐰 경미

#35 fix: tuist 카카오 API 키 설정 및 .DS_Store 삭제 (#34)
  .DS_Store
  .gitignore
  14th-team5-iOS/App/Project.swift
  14th-team5-iOS/XCConfig/dev.xcconfig
  14th-team5-iOS/XCConfig/prd.xcconfig
  14th-team5-iOS/XCConfig/shared.xcconfig
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  pippi.xcworkspace/contents.xcworkspacedata
Labels: ⚒️ SETTING, 🐭 건희

#37 Feat: 메인 캘린더 UI 구현
  14th-team5-iOS/App/Sources/Extensions/Date+Ext.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/CalendarPageCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/CalendarPageViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/ImageMonthCalendarCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/PlaceholderCalendarCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarDescriptionPopoverViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarViewController.swift
Labels: ✨ FEATURE, 🐼 건우

#41 feat: add feed collectionview (#36)
  14th-team5-iOS/App/Resources/Assets.xcassets/Shutter.imageset/Contents.json
  14th-team5-iOS/App/Resources/Assets.xcassets/Shutter.imageset/Shutter.svg
  14th-team5-iOS/App/Sources/Application/SceneDelegate.swift
  14th-team5-iOS/App/Sources/Presentation/Main/Model/SectionOfFamily.swift
  14th-team5-iOS/App/Sources/Presentation/Main/Model/SectionOfFeed.swift
  14th-team5-iOS/App/Sources/Presentation/Main/ViewControllers/MainViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Main/Views/FeedCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Main/Views/ProfileView.swift
  14th-team5-iOS/Core/Sources/Base/BaseViewController.swift
Labels: ✨ FEATURE, 🐰 경미

#39 Feat: 주간 캘린더 UI 구현, UIStackView+Ext 추가
  14th-team5-iOS/App/Sources/Extensions/Date+Ext.swift
  14th-team5-iOS/App/Sources/Extensions/UIStackView+Ext.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarFeedViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/CalendarPageCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/ImageMonthCalendarCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarDescriptionPopoverViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarFeedViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarViewController.swift
Labels: ✨ FEATURE, 🐼 건우

#45 feat: 메인 뷰 작업을 마무리합니다.
  14th-team5-iOS/App/Resources/Assets.xcassets/Calendar.imageset/Calendar.svg
  14th-team5-iOS/App/Resources/Assets.xcassets/Calendar.imageset/Contents.json
  14th-team5-iOS/App/Resources/Assets.xcassets/Profile.imageset/Contents.json
  14th-team5-iOS/App/Resources/Assets.xcassets/Profile.imageset/Profile.svg
  14th-team5-iOS/App/Sources/Presentation/Main/ViewControllers/MainViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Main/Views/FamilyCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Main/Views/FeedCollectionReusableView.swift
  14th-team5-iOS/App/Sources/Presentation/Main/Views/FeedCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Main/Views/ProfileView.swift
Labels: ✨ FEATURE, 🐰 경미

#50 Style: CalendarViewController.swift 등 코드 스타일 수정, Global State 적용
  14th-team5-iOS/App/Sources/Application/SceneDelegate.swift
  14th-team5-iOS/App/Sources/Extensions/UIStackView+Ext.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/DelegateProxy/RxFSCalendarDelegateProxy.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarPageViewCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/ImageCalendarCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/CalendarPageCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/ImageCalendarCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/PlaceholderCalendarCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarDescriptionPopoverViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarFeedViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Strings/CalendarVC.swift
  14th-team5-iOS/App/Sources/Presentation/Strings/CalenderCell.swift
  14th-team5-iOS/Core/Sources/GlobalState/BaseGlobalState.swift
  14th-team5-iOS/Core/Sources/GlobalState/CalendarGlobalState.swift
  14th-team5-iOS/Core/Sources/GlobalState/GlobalStateProvider.swift
Labels: ✨ FEATURE, 🐼 건우

#43 feat: 회원가입 기본 로직 구현 (추가 구현예정)
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/AccountSignUp.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Reactor/AccountSignUpReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Reactor/DateOfBirthReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Reactor/NicknameInputReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Reactor/ProfileImageSelctReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/ViewControllers/AccountSignUpViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Views/DateOfBirthInputView.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Views/NicknameInputView.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Views/ProfileImageSelectView.swift
  14th-team5-iOS/Core/Sources/Base/BaseView.swift
Labels: ✨ FEATURE, 🐭 건희

#53 feat: Custom Camera UI 구현
  14th-team5-iOS/App/Project.swift
  14th-team5-iOS/App/Sources/Extensions/UIButton+Ext.swift
  14th-team5-iOS/App/Sources/Extensions/UIImage+Ext.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraViewReactor.swift
  14th-team5-iOS/Data/Sources/Camera/Repository/CameraViewRepository.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/flash.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/flash.imageset/bolt.fill.png
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/shutter.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/shutter.imageset/Shutter.png
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/toggle.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/toggle.imageset/reverse.png
  pippi.xcworkspace/contents.xcworkspacedata
  pippi.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
Labels: ✨ FEATURE, 🦊 도현

#57 feat: 피드 자세히 보기 뷰 구현
  14th-team5-iOS/App/Sources/Extensions/UICollectionViewLayoutAttributes+Ext.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Model/SectionOfFeedDetail.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Reactor/EmojiReactor.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/ViewControllers/FeedDetailViewController.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Views/EmojiCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Views/FeedDetailCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Views/RightAlignedCollectionView.swift
  14th-team5-iOS/App/Sources/Presentation/Main/ViewControllers/MainViewController.swift
  14th-team5-iOS/Core/Sources/Base/BaseCollectionViewCell.swift
Labels: ✨ FEATURE, 🐰 경미

#59 feat: 이모지 뷰 수정
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Views/EmojiView.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Views/FeedDetailCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Views/RightAlignedCollectionView.swift
Labels: ✨ FEATURE, 🐰 경미

#64 feat: CameraDisplayViewController UI 구현
  14th-team5-iOS/App/Project.swift
  14th-team5-iOS/App/Sources/Extensions/UIViewController+Ext.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraDisplayViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Dependency/CameraDisplayDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraDisplayViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Main/ViewControllers/MainViewController.swift
  14th-team5-iOS/Data/Sources/Camera/Repository/CameraDisplayViewRepository.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/archive.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/archive.imageset/archive.png
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/confirm.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/confirm.imageset/confirm.png
Labels: ✨ FEATURE, 🦊 도현

#61 Feat: 초대 링크 복사 화면 UI 구현, Firebase 세팅
  14th-team5-iOS/App/Project.swift
  14th-team5-iOS/App/Resources/GoogleService-Info.plist
  14th-team5-iOS/App/Sources/Application/AppDelegate.swift
  14th-team5-iOS/App/Sources/Extensions/UIStackView+Ext.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/DelegateProxy/RxFSCalendarDelegateProxy.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/ImageCalendarCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/CalendarPageCell.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/Reactor/LinkShareViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/Reactor/YourFamilProfileCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/Strings/LinkShareCell.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/Strings/LinkShareVC.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/View/YourFamilyProfileCell.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/ViewController/LinkShareViewController.swift
  14th-team5-iOS/Core/Sources/GlobalState/CalendarGlobalState.swift
  App.entitlements
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Modular+Templates.swift
  Tuist/ProjectDescriptionHelpers/ModuleType+Templates.swift
  pippi.xcworkspace/contents.xcworkspacedata
  pippi.xcworkspace/xcshareddata/xcschemes/pippi-Workspace.xcscheme
Labels: ✨ FEATURE, 🐼 건우

#66 Feat: 초대 링크 복사 화면 UI 수정, 공유 시트 구현
  14th-team5-iOS/App/Sources/Extensions/UIViewController+Ext.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarPageViewCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/CalendarPageCell.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/Reactor/LinkShareViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/Strings/LinkShareVC.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/ViewController/LinkShareViewController.swift
  14th-team5-iOS/Core/Sources/GlobalState/ActivityGlobalState.swift
  14th-team5-iOS/Core/Sources/GlobalState/CalendarGlobalState.swift
  14th-team5-iOS/Core/Sources/GlobalState/GlobalStateProvider.swift
  14th-team5-iOS/Core/Sources/SharePanel/CopyInvitationUrlActivity.swift
  14th-team5-iOS/Core/Sources/SharePanel/UrlActivityItemSource.swift
Labels: ✨ FEATURE, 🐼 건우

#68 feat: Token 관리를 위한 Repo 생성
  14th-team5-iOS/App/Sources/Application/AppDelegate.swift
  14th-team5-iOS/Core/Sources/App/App.swift
  14th-team5-iOS/Core/Sources/Reactive/RxObject.swift
  14th-team5-iOS/Core/Sources/Reactive/RxUtils.swift
  14th-team5-iOS/Core/Sources/Token/TokenRepository.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/ModuleType+Templates.swift
  Tuist/ProjectDescriptionHelpers/Package+Templates.swift
  pippi.xcworkspace/xcshareddata/xcschemes/pippi-Workspace.xcscheme
Labels: ✨ FEATURE, 🐭 건희

#70 Feat: 팝오버 공통 모듈 구현, API 통신 기본 구현 및 세팅
  14th-team5-iOS/App/Sources/Extensions/UIViewController+Ext.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Strings/CalendarVC.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Strings/CalenderCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarDescriptionPopoverViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarViewController.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/Reactor/LinkShareViewReactor.swift
  14th-team5-iOS/Core/Sources/Popover/CalendarDescriptionPopoverViewController.swift
  14th-team5-iOS/Data/Sources/Calendar/Repository/CalendarViewRepository.swift
  14th-team5-iOS/Data/Sources/LinkShare/Repository/LinkShareViewRepository.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: ✨ FEATURE, 🐼 건우

#71 feat: 이모지 선택
  14th-team5-iOS/App/Resources/Assets.xcassets/Calendar.imageset/Calendar.svg
  14th-team5-iOS/App/Resources/Assets.xcassets/Calendar.imageset/Contents.json
  14th-team5-iOS/App/Resources/Assets.xcassets/Profile.imageset/Profile.svg
  14th-team5-iOS/App/Resources/Assets.xcassets/Shutter.imageset/Contents.json
  14th-team5-iOS/App/Resources/Assets.xcassets/Shutter.imageset/Shutter.svg
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Model/Emojis.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Reactor/EmojiReactor.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Reactor/FeedDetailReactor.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Views/EmojiButton.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Views/EmojiView.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Views/FeedDetailCollectionViewCell.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/DotEllipse.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/DotEllipse.imageset/Ellipse 2063.svg
Labels: ✨ FEATURE, 🐰 경미

#73 feat: CameraDisplayViewController Edit View 기능 개발
  14th-team5-iOS/App/Sources/Extensions/Reactive+Ext.swift
  14th-team5-iOS/App/Sources/Extensions/UIImage+Ext.swift
  14th-team5-iOS/App/Sources/Extensions/UITextField+Ext.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraDisplayViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Cell/CellReactor/DisplayEditCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Cell/DisplayEditCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/DataSources/DisplayEditSectionModel.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraDisplayViewReactor.swift
  14th-team5-iOS/Data/Sources/Camera/Repository/CameraDisplayViewRepository.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/clear.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/clear.imageset/clear.png
Labels: ✨ FEATURE, 🦊 도현

#76 feat: MyPage Setting 화면 UI 구현
  14th-team5-iOS/App/Sources/Presentation/Privacy/Cell/CellReactor/PrivacyCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/Cell/DataSources/PrivacySectionModel.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/Cell/PrivacyAuthorizationTableViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/Cell/PrivacyTableViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/Dependency/PrivacyDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/PrivacyViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/Reactor/PrivacyViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/ReusableView/PrivacyAuthorizationHeaderFooterView.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/ReusableView/PrivacyHeaderFooterView.swift
  14th-team5-iOS/Data/Sources/Privacy/Repository/PrivacyViewRepository.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/arrow.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/arrow.imageset/arrow.png
  14th-team5-iOS/Domain/Sources/Privacy/Privacy.swift
  App.entitlements
  pippi.xcworkspace/contents.xcworkspacedata
Labels: ✨ FEATURE, 🦊 도현

#77 feat: 온보딩 화면 개발 (기능)
  14th-team5-iOS/App/Sources/Application/AppDelegate.swift
  14th-team5-iOS/App/Sources/Presentation/OnBoarding/OnBoardigViewController.swift
  14th-team5-iOS/App/Sources/Presentation/OnBoarding/OnBoarding.swift
  14th-team5-iOS/App/Sources/Presentation/OnBoarding/OnBoardingReactor.swift
  14th-team5-iOS/App/Sources/Presentation/OnBoarding/OnBoardingStrings.swift
  14th-team5-iOS/App/Sources/Presentation/OnBoarding/OnBoardingViewCell.swift
  14th-team5-iOS/Core/Sources/Reactive/RxUtils.swift
Labels: ✨ FEATURE, 🐭 건희

#86 feat: MyPage ProfileView UI 구현
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Reactor/FeedDetailReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Cell/CellReactor/ProfileFeedCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Cell/ProfileFeedCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/DataSources/ProfileFeedSectionModel.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Dependency/ProfileDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/ViewController.swift
  14th-team5-iOS/Core/Sources/Extensions/Bundle+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/Date+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/DateFormatter+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/Reactive+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/String+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UIButton+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UICollectionViewLayoutAttributes+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UIImage+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UIStackView+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UITextField+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UIView+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UIViewController+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UserDefaults+Ext.swift
  14th-team5-iOS/Core/Sources/ShareView/BibbiProfileView.swift
  14th-team5-iOS/Core/Sources/ShareView/Reactor/BibbiProfileViewReactor.swift
  14th-team5-iOS/Data/Sources/Profile/Repository/ProfileViewRepository.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/camera.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/camera.imageset/camera.png
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/edit.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/edit.imageset/edit.png
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/privacy.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/privacy.imageset/privacy.png
Labels: ✨ FEATURE, 🦊 도현

#89 Feat: 추억 캘린더 및 친구 추가 화면 UI 수정, 팝오버 메서드 동작 수정
  14th-team5-iOS/App/Sources/Presentation/Calendar/Dependency/CalendarFeedDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarFeedViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Strings/CalendarVC.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Strings/CalenderCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/CalendarPageCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarFeedViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarViewController.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/Dependency/AddFamiliyDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/Dependency/LinkShareDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/Reactor/AddFamiliyViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/Strings/AddFamiliyCell.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/Strings/AddFamiliyVC.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/Strings/LinkShareVC.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/View/YourFamilyProfileCell.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/ViewController/AddFamiliyViewController.swift
  14th-team5-iOS/App/Sources/Presentation/LinkShare/ViewController/LinkShareViewController.swift
  14th-team5-iOS/Core/Sources/Base/BaseGlobalState.swift
  14th-team5-iOS/Core/Sources/Extensions/UIViewController+Ext.swift
  14th-team5-iOS/Core/Sources/Popover/CalendarDescriptionPopoverViewController.swift
  14th-team5-iOS/Data/Sources/LinkShare/Repository/AddFamiliyViewRepository.swift
  pippi.xcworkspace/contents.xcworkspacedata
Labels: ✨ FEATURE, 🐼 건우

#97 Feat/#63: 주간 캘린더에 피드 UI 구현, 캘린더 셀 UI 수정, RoundedToastView 메서드 추가
  14th-team5-iOS/App/Sources/Presentation/AddFamiliy/ViewController/AddFamiliyViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/ImageCalendarCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Strings/CalenderCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/CalendarPageCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/ImageCalendarCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarFeedViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarViewController.swift
  14th-team5-iOS/Core/Sources/Extensions/UINavigationController+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UIViewController+Ext.swift
  14th-team5-iOS/Core/Sources/SharePanel/CopyInvitationUrlActivity.swift
Labels: ✨ FEATURE, 🐼 건우

#95 Feat/#24 kakao login 셋팅 및 개발
  14th-team5-iOS/App/Sources/Application/AppDelegate.swift
  14th-team5-iOS/App/Sources/Application/SceneDelegate.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignIn/AccountSignInDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignIn/AccountSignInReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignIn/AccountSignInViewController.swift
  14th-team5-iOS/Data/Sources/API/API.swift
  14th-team5-iOS/Data/Sources/API/APIWorker.swift
  14th-team5-iOS/Data/Sources/API/Codable+Ext.swift
  14th-team5-iOS/Data/Sources/Account/AccountAPI/AccountAPIWorker.swift
  14th-team5-iOS/Data/Sources/Account/AccountAPI/AccountAPIs.swift
  14th-team5-iOS/Data/Sources/Account/AccountRepository/AccountRepository.swift
  14th-team5-iOS/Data/Sources/Camera/Repository/CameraDisplayViewRepository.swift
  14th-team5-iOS/Data/Sources/Service/AccountSignInHelper.swift
  14th-team5-iOS/Data/Sources/Service/AccountSignInHelperConfig.swift
  14th-team5-iOS/Data/Sources/Service/AccountSignInHelperType.swift
  14th-team5-iOS/Data/Sources/Service/Apple/AppleService+Rx.swift
  14th-team5-iOS/Data/Sources/Service/Apple/AppleSignInHelper.swift
  14th-team5-iOS/Data/Sources/Service/Kakao/KakaoService+Rx.swift
  14th-team5-iOS/Data/Sources/Service/Kakao/KakaoSignInHelper.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/appleLogin.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/appleLogin.imageset/appleLogin@2x.png
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/appleLogin.imageset/appleLogin@3x.png
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/kakaoLogin.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/kakaoLogin.imageset/kakaoLogin@2x.png
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/kakaoLogin.imageset/kakaoLogin@3x.png
  14th-team5-iOS/Domain/Sources/Account/AccessToken.swift
  14th-team5-iOS/Domain/Sources/Account/AccountSignIn/AccountSignInStateInfo.swift
  14th-team5-iOS/Domain/Sources/Account/SNS.swift
  Tuist/ProjectDescriptionHelpers/ModuleType+Templates.swift
  pippi.xcworkspace/contents.xcworkspacedata
Labels: ✨ FEATURE, 🐭 건희

#98 Feat/#88: 친구 추가 화면 통신 구현
  14th-team5-iOS/App/Sources/Presentation/AddFamiliy/DataSource/FamiliyMemberProfile.swift
  14th-team5-iOS/App/Sources/Presentation/AddFamiliy/Dependency/AddFamiliyDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/AddFamiliy/Reactor/AddFamiliyViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/AddFamiliy/Reactor/YourFamilProfileCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/AddFamiliy/View/YourFamilyProfileCell.swift
  14th-team5-iOS/App/Sources/Presentation/AddFamiliy/ViewController/AddFamiliyViewController.swift
  14th-team5-iOS/Data/Sources/API/API.swift
  14th-team5-iOS/Data/Sources/AddFamiliy/AddFamiliyAPI/AddFamiliyAPIWorker.swift
  14th-team5-iOS/Data/Sources/AddFamiliy/AddFamiliyAPI/AddFamiliyAPIs.swift
  14th-team5-iOS/Data/Sources/AddFamiliy/AddFamiliyAPI/DataMapping/FamiliyInvitationLinkResponseDTO+Mapping.swift
  14th-team5-iOS/Data/Sources/AddFamiliy/AddFamiliyAPI/DataMapping/PaginationResponseFamiliyMemberProfileDTO+Mapping.swift
  14th-team5-iOS/Data/Sources/AddFamiliy/Repository/AddFamiliyRepository.swift
  14th-team5-iOS/Data/Sources/LinkShare/Repository/AddFamiliyViewRepository.swift
  14th-team5-iOS/Domain/Sources/AddFamiliy/Entity/FamiliyInvitationLinkResponse.swift
  14th-team5-iOS/Domain/Sources/AddFamiliy/Entity/FamiliyMemberProfileResponse.swift
  pippi.xcworkspace/contents.xcworkspacedata
Labels: ✨ FEATURE, 🐼 건우

#107 feat: 포스트 이모지 선택 기능 추가 및 뷰 수정
  14th-team5-iOS/App/Sources/Application/SceneDelegate.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarFeedViewController.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Model/Emojis.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Model/SectionOfFeedDetail.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Reactor/EmojiReactor.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Reactor/PostReactor.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/ViewControllers/FeedDetailViewController.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Views/EmojiCountButton.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Views/FeedDetailCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Views/PostCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Views/PostNavigationView.swift
  14th-team5-iOS/App/Sources/Presentation/FeedDetail/Views/SelectableEmojiButton.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: ✨ FEATURE, 🐰 경미

#104 feat: 위젯 기본 화면 구현완료
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/Family.swift
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyService.swift
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyWidget.swift
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyWidgetEntry.swift
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyWidgetTimelineProvider.swift
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyWidgetView.swift
  pippi.xcworkspace/contents.xcworkspacedata
Labels: ✨ FEATURE, 🐭 건희

#114 Fix/#113: 빌드 에러 수정(긴급)
  14th-team5-iOS/App/Sources/Presentation/AddFamily/Dependency/AddFamilyDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/AddFamily/ViewController/AddFamilyViewController.swift
Labels: 🐞 BUG, 🐼 건우

#118 feat: 주간 추억 캘린더 API 통신 구현
  14th-team5-iOS/App/Sources/Presentation/AddFamily/Reactor/AddFamilyViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/DelegateProxy/RxFSCalendarDelegateProxy.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Dependency/CalendarPostDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Dependency/ImageCalendarCellDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarPageViewCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarPostViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/ImageCalendarCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/CalendarPageCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/ImageCalendarCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarPostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarViewController.swift
  14th-team5-iOS/Core/Sources/Extensions/Date+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/Int+Ext.swift
  14th-team5-iOS/Core/Sources/GlobalState/CalendarGlobalState.swift
  14th-team5-iOS/Data/Sources/AddFamiliy/Repository/AddFamilyRepository.swift
  14th-team5-iOS/Data/Sources/Calendar/Repository/CalendarRepository.swift
  14th-team5-iOS/Domain/Sources/Calendar/Entity/ArrayResponseCalendarResponse.swift
  pippi.xcworkspace/contents.xcworkspacedata
Labels: ✨ FEATURE, 🐼 건우

#119 feat: 회원가입 프로세스 개발
  14th-team5-iOS/App/Sources/Application/AppDelegate.swift
  14th-team5-iOS/App/Sources/Application/SceneDelegate.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignIn/AccountSignInReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignIn/AccountSignInViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/AccountSignUpStrings.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Dependeyncy/AccountSignUpDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Reactor/AccountSignUpReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Reactor/DateOfBirthReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Reactor/NicknameInputReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Reactor/ProfileImageSelctReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/ViewControllers/AccountDateViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/ViewControllers/AccountNicknameViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/ViewControllers/AccountProfileViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/ViewControllers/AccountSignUpViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Views/DateOfBirthInputView.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Views/NicknameInputView.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Views/ProfileImageSelectView.swift
  14th-team5-iOS/App/Sources/Presentation/OnBoarding/Dependency/OnBoardingDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/OnBoarding/OnBoardingReactor.swift
  14th-team5-iOS/App/Sources/Presentation/OnBoarding/OnBoardingViewController.swift
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyService.swift
  14th-team5-iOS/Core/Sources/Base/BasePageViewController.swift
  14th-team5-iOS/Core/Sources/Extensions/UIPageViewController+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UserDefaults+Ext.swift
  14th-team5-iOS/Data/Sources/Account/AccountAPI/AccountAPIWorker.swift
  14th-team5-iOS/Data/Sources/Account/AccountAPI/AccountAPIs.swift
  14th-team5-iOS/Data/Sources/Account/AccountRepository/AccountRepository.swift
  14th-team5-iOS/Data/Sources/Service/AccountSignInHelper.swift
  14th-team5-iOS/Data/Sources/Service/Kakao/KakaoSignInHelper.swift
  14th-team5-iOS/Domain/Sources/Account/AccessToken.swift
  14th-team5-iOS/Domain/Sources/Account/AccountSignInStateInfo.swift
  Tuist/ProjectDescriptionHelpers/ModuleType+Templates.swift
Labels: ✨ FEATURE, 🐭 건희

#122 feat: 포스트 리스트 API 추가
  14th-team5-iOS/App/Sources/Presentation/Home/Dependency/HomeDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Model/SectionOfFeed.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/HomeViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/HomeViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Views/FeedCollectionViewCell.swift
  14th-team5-iOS/Data/Sources/Post/PostList/DTO/PostListDTO.swift
  14th-team5-iOS/Data/Sources/Post/PostList/PostListAPI/PostListAPIWorker.swift
  14th-team5-iOS/Data/Sources/Post/PostList/PostListAPI/PostListAPIs.swift
  14th-team5-iOS/Domain/Sources/Family/SearchFamily/Interfaces/SearchFamilyRepository.swift
  14th-team5-iOS/Domain/Sources/Post/PostList/Entities/PostListData.swift
  14th-team5-iOS/Domain/Sources/Post/PostList/Entities/PostListQuery.swift
  14th-team5-iOS/Domain/Sources/Post/PostList/Interfaces/PostListRepository.swift
  14th-team5-iOS/Domain/Sources/Post/PostList/UseCases/PostListUseCase.swift
Labels: ✨ FEATURE, 🐰 경미

#121 feat: 친구 추가 화면 세부 UI 수정
  14th-team5-iOS/App/Sources/Presentation/AddFamily/DataSource/FamilyMemberProfile.swift
  14th-team5-iOS/App/Sources/Presentation/AddFamily/Dependency/FamilyMemberProfileCellDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/AddFamily/Reactor/AddFamilyViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/AddFamily/Reactor/FamilyMemberProfileCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/AddFamily/Strings/AddFamilyVC.swift
  14th-team5-iOS/App/Sources/Presentation/AddFamily/View/FamilyMemberProfileCell.swift
  14th-team5-iOS/App/Sources/Presentation/AddFamily/ViewController/AddFamilyViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Dependency/CalendarFeedDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarPostViewController.swift
  14th-team5-iOS/Core/Sources/Extensions/String+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UILabel+Ext.swift
  14th-team5-iOS/Data/Sources/Family/DTO/FamilySearchDTO.swift
  14th-team5-iOS/Data/Sources/Family/FamilyAPI/DataMapping/FamilyInvitationLinkResponseDTO+Mapping.swift
  14th-team5-iOS/Data/Sources/Family/FamilyAPI/DataMapping/PaginationResponseFamiliyMemberProfileDTO+Mapping.swift
  14th-team5-iOS/Data/Sources/Family/FamilyAPI/FamilyAPIWorker.swift
  14th-team5-iOS/Data/Sources/Family/FamilyAPI/FamilyAPIs.swift
  14th-team5-iOS/Data/Sources/Family/Repository/FamiliyRepository.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/envelope.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/envelope.imageset/레이어_1.svg
Labels: ✨ FEATURE, 🐼 건우

#127 feat: 공통 TypeSystemLabel 추가
  14th-team5-iOS/App/Sources/Presentation/AddFamily/View/FamilyMemberProfileCell.swift
  14th-team5-iOS/App/Sources/Presentation/AddFamily/ViewController/AddFamilyViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/CalendarPageCell.swift
  14th-team5-iOS/Core/Sources/Activity/CopyInvitationUrlActivity.swift
  14th-team5-iOS/Core/Sources/Activity/UrlActivityItemSource.swift
  14th-team5-iOS/Core/Sources/Extensions/UILabel+Ext.swift
  14th-team5-iOS/Core/Sources/Popover/DescriptionPopoverViewController.swift
  14th-team5-iOS/Core/Sources/UILabel/TypeSystemLabel.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/envelope.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/envelope.imageset/envelope.svg
Labels: ✨ FEATURE, 🐼 건우

#126 feat: ProfileView 회원 조회 API 연동 및 UI 디자인 수정 With CameraView,CameraDisplayView UseCase 추가
  14th-team5-iOS/App/Sources/Application/SceneDelegate.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Dependency/CameraDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Dependency/CameraDisplayDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraDisplayViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/HomeViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Cell/CellReactor/ProfileFeedCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Cell/ProfileFeedCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Dependency/ProfileDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileViewReactor.swift
  14th-team5-iOS/Core/Sources/Extensions/AVCapturePhotoOutput+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/DateFormatter+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/NSItemProvider+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/Notification+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/Reactive+Ext.swift
  14th-team5-iOS/Core/Sources/ShareView/BibbiProfileView.swift
  14th-team5-iOS/Core/Sources/ShareView/Reactor/BibbiProfileViewReactor.swift
  14th-team5-iOS/Data/Sources/API/API.swift
  14th-team5-iOS/Data/Sources/API/APIWorker.swift
  14th-team5-iOS/Data/Sources/API/Codable+Ext.swift
  14th-team5-iOS/Data/Sources/Camera/CameraAPI/CameraAPIWorker.swift
  14th-team5-iOS/Data/Sources/Camera/CameraAPI/CameraAPIs.swift
  14th-team5-iOS/Data/Sources/Camera/Repositories/CameraDisplayViewRepository.swift
  14th-team5-iOS/Data/Sources/Camera/Repositories/CameraViewRepository.swift
  14th-team5-iOS/Data/Sources/Camera/Repository/CameraViewRepository.swift
  14th-team5-iOS/Data/Sources/Profile/ProfileAPI/ProfileAPIWorker.swift
  14th-team5-iOS/Data/Sources/Profile/ProfileAPI/ProfileAPIs.swift
  14th-team5-iOS/Data/Sources/Profile/Repositories/ProfileViewRepository.swift
  14th-team5-iOS/Data/Sources/Profile/Repository/ProfileViewRepository.swift
  14th-team5-iOS/Domain/Sources/Camera/Interfaces/CameraDisplayViewInterface.swift
  14th-team5-iOS/Domain/Sources/Camera/Interfaces/CameraViewInterface.swift
  14th-team5-iOS/Domain/Sources/Camera/UseCases/CameraDisplayViewUseCase.swift
  14th-team5-iOS/Domain/Sources/Camera/UseCases/CameraViewUseCase.swift
  14th-team5-iOS/Domain/Sources/Profile/DataMapping/ProfileMemberDTO.swift
  14th-team5-iOS/Domain/Sources/Profile/DataMapping/ProfilePostDTO.swift
  14th-team5-iOS/Domain/Sources/Profile/Entity/ProfileMemberResponse.swift
  14th-team5-iOS/Domain/Sources/Profile/Entity/ProfilePostResponse.swift
  14th-team5-iOS/Domain/Sources/Profile/Interfaces/ProfileViewInterface.swift
  14th-team5-iOS/Domain/Sources/Profile/Parameters/ProfileImageEditParameter.swift
  14th-team5-iOS/Domain/Sources/Profile/Parameters/ProfilePostParameter.swift
  14th-team5-iOS/Domain/Sources/Profile/UseCases/ProfileViewUseCase.swift
Labels: ✨ FEATURE, 🦊 도현

#136 fix: CameraDisplayViewRepository File 제거
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/ViewControllers/AccountProfileViewController.swift
  14th-team5-iOS/Data/Sources/Camera/Repository/CameraDisplayViewRepository.swift
  Tuist/ProjectDescriptionHelpers/ModuleType+Templates.swift
  pippi.xcworkspace/contents.xcworkspacedata
Labels: 🐞 BUG, 🦊 도현

#128 feat: 홈 디자인 적용
  14th-team5-iOS/App/Sources/Presentation/Home/Model/String/HomeCGFloat.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Model/String/HomeString.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Model/String/HomeStringLiterals.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/HomeViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/HomeViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Views/FeedCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Views/InviteFamilyView.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Views/NoPostTodayView.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Views/ProfileView.swift
  14th-team5-iOS/Core/Sources/Extensions/Int+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UIViewController+Ext.swift
  14th-team5-iOS/Core/Sources/Popover/BalloonView.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/Bibbi.imageset/Bibbi.svg
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/Bibbi.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/EmptyCaseGraphicEmoji.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/EmptyCaseGraphicEmoji.imageset/Group 1000003753.svg
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/camerButton.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/camerButton.imageset/btn_camera.svg
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/envelopeBackground.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/envelopeBackground.imageset/Frame 427322941 (1).svg
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/flash.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/flash.imageset/flash.svg
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/invite.imageset/Frame 427322941.svg
  14th-team5-iOS/Domain/Sources/Post/PostList/Entities/PostListData.swift
Labels: ✨ FEATURE, 🐰 경미

#134 feat: 월간 캘린더 UI 수정, UseCase 추가 및 UIFont+Ext 추가
  14th-team5-iOS/App/Sources/Application/AppDelegate.swift
  14th-team5-iOS/App/Sources/Presentation/AddFamily/Dependency/AddFamilyDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Dependency/CalendarDIConatainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Dependency/CalendarPageCellDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Dependency/CalendarPostDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Dependency/ImageCalendarCellDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarPageViewCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarPostViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/ImageCalendarCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Strings/CalenderCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/CalendarPageCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/ImageCalendarCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarPostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/HomeViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/InviteFamily/DataSource/FamilyMemberProfile.swift
  14th-team5-iOS/App/Sources/Presentation/InviteFamily/Dependency/FamilyMemberProfileCellDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/InviteFamily/Dependency/InviteFamilyDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/InviteFamily/Reactor/FamilyMemberProfileCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/InviteFamily/Reactor/InviteFamilyViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/InviteFamily/Strings/AddFamilyCell.swift
  14th-team5-iOS/App/Sources/Presentation/InviteFamily/Strings/AddFamilyVC.swift
  14th-team5-iOS/App/Sources/Presentation/InviteFamily/View/FamilyMemberProfileCell.swift
  14th-team5-iOS/App/Sources/Presentation/InviteFamily/ViewController/InviteFamilyViewController.swift
  14th-team5-iOS/Core/Sources/Activity/CopyInvitationUrlActivity.swift
  14th-team5-iOS/Core/Sources/Base/BaseGlobalState.swift
  14th-team5-iOS/Core/Sources/Extensions/UIFont+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UIViewController+Ext.swift
  14th-team5-iOS/Core/Sources/GlobalState/GlobalStateProvider.swift
  14th-team5-iOS/Core/Sources/UILabel/TypeSystemLabel.swift
  14th-team5-iOS/Data/Sources/Calendar/CalendarAPI/DataMapping/ArrayResponseCalendarResponseDTO.swift
  14th-team5-iOS/Data/Sources/Calendar/Repository/CalendarRepository.swift
  14th-team5-iOS/Data/Sources/Family/FamilyAPI/DataMapping/FamilyInvitationLinkResponseDTO.swift
  14th-team5-iOS/Data/Sources/Family/FamilyAPI/DataMapping/PaginationResponseFamiliyMemberProfileDTO.swift
  14th-team5-iOS/Data/Sources/Family/Repository/FamilyRepository.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/greenSmileEmoji.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/greenSmileEmoji.imageset/greenSmileEmoji.svg
  14th-team5-iOS/Domain/Sources/Calendar/Entities/ArrayResponseCalendarResponse.swift
  14th-team5-iOS/Domain/Sources/Calendar/Interfaces/Repositories/CalendarRepository.swift
  14th-team5-iOS/Domain/Sources/Calendar/UseCases/CalendarUseCase.swift
  14th-team5-iOS/Domain/Sources/Family/InviteFamily/Entities/FamilyInvitationLinkResponse.swift
  14th-team5-iOS/Domain/Sources/Family/InviteFamily/Entities/FamilyMemberProfileResponse.swift
  14th-team5-iOS/Domain/Sources/Family/InviteFamily/Interfaces/Repositories/FamilyRepository.swift
  14th-team5-iOS/Domain/Sources/Family/InviteFamily/UseCases/InviteFamilyViewUseCase.swift
  pippi.xcworkspace/contents.xcworkspacedata
Labels: ✨ FEATURE, 🐼 건우

#137 feat: ProfileView UI Design 수정 및 닉네임 변경 API 추가
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Dependeyncy/AccountSignUpDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Reactor/AccountSignUpReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/ViewControllers/AccountNicknameViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraDisplayViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/Cell/PrivacyAuthorizationTableViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/Cell/PrivacyTableViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/PrivacyViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/ReusableView/PrivacyAuthorizationHeaderFooterView.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/ReusableView/PrivacyHeaderFooterView.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Cell/ProfileFeedCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileViewController.swift
  14th-team5-iOS/Core/Sources/ShareView/BibbiProfileView.swift
  14th-team5-iOS/Data/Sources/Account/AccountAPI/AccountAPIWorker.swift
  14th-team5-iOS/Data/Sources/Account/AccountAPI/AccountAPIs.swift
  14th-team5-iOS/Data/Sources/Account/AccountRepository/AccountRepository.swift
  14th-team5-iOS/Data/Sources/Camera/Repositories/CameraDisplayViewRepository.swift
  14th-team5-iOS/Domain/Sources/Account/DataMapping/AccountNickNameEditDTO.swift
  14th-team5-iOS/Domain/Sources/Account/Entity/AccountNickNameEditResponse.swift
  14th-team5-iOS/Domain/Sources/Account/Parameters/AccountNickNameEditParameter.swift
  14th-team5-iOS/Domain/Sources/Camera/Entity/CameraDisplayPostResponse.swift
Labels: ✨ FEATURE, 🦊 도현

#141 fix: ProfileViewController Feed CollectionView Pagination issue 수정
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileViewReactor.swift
  14th-team5-iOS/Data/Sources/Profile/Repositories/ProfileViewRepository.swift
  14th-team5-iOS/Domain/Sources/Profile/UseCases/ProfileViewUseCase.swift
Labels: 🐞 BUG, 🦊 도현
