Repository depromeet/14th-team5-iOS, pull requests merged in 2024-05, with the labels that each got.

#497 fix: ci/cd Branch 네이밍 수정 및 STG,PRD 배포 변경
  .github/workflows/swift.yml
Labels: ⚒️ SETTING, 🦊 도현

#492 feat: Home 재촉하기 기능 구현
  14th-team5-iOS/App/Sources/Presentation/Home/Dependency/MainViewDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Model/FamilySection.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/Cell/MainFamilyCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/MainViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/MainFamilyViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/MainViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Views/MainFamilyCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/PostComment/DataSource/CommentSectionModel.swift
  14th-team5-iOS/App/Sources/Presentation/PostComment/DataSource/PostCommentSectionModel.swift
  14th-team5-iOS/App/Sources/Presentation/PostComment/Dependency/PostCommentDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/PostComment/Reactor/CommentViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostComment/ViewController/PostCommentViewController.swift
  14th-team5-iOS/Core/Sources/GlobalState/GlobalStateProvider.swift
  14th-team5-iOS/Core/Sources/GlobalState/HomeService.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/yellowPaperPlane.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/yellowPaperPlane.imageset/icon-paper-plane.svg
  14th-team5-iOS/Domain/Sources/Main/Entities/FamilySection.swift
  14th-team5-iOS/Domain/Sources/Main/Entities/MainData.swift
  Bibbi.xcworkspace/xcshareddata/xcschemes/Bibbi-Workspace.xcscheme
Labels: ✨ FEATURE, 🐼 건우

#495 feat: Mission Camera Layout 추가
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraDisplayViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Dependency/CameraDisplayDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraDisplayViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/MainViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/PostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileDetailViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileViewController.swift
  14th-team5-iOS/Core/Sources/ShareView/BibbiMissionView.swift
  14th-team5-iOS/Data/Sources/Camera/CameraAPI/CameraAPIWorker.swift
  14th-team5-iOS/Data/Sources/Camera/CameraAPI/CameraAPIs.swift
  14th-team5-iOS/Data/Sources/Camera/DataMapping/CameraDisplayPostDTO.swift
  14th-team5-iOS/Data/Sources/Camera/DataMapping/CameraTodayMissionDTO.swift
  14th-team5-iOS/Data/Sources/Camera/Repositories/CameraDisplayViewRepository.swift
  14th-team5-iOS/Data/Sources/Camera/Repositories/CameraViewRepository.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/missionTitleBadge.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/missionTitleBadge.imageset/missionTitleBadge.svg
  14th-team5-iOS/Domain/Sources/Camera/Entity/CameraDisplayPostResponse.swift
  14th-team5-iOS/Domain/Sources/Camera/Entity/CameraMissionFeedQuery.swift
  14th-team5-iOS/Domain/Sources/Camera/Entity/CameraTodayMissionResponse.swift
  14th-team5-iOS/Domain/Sources/Camera/Interfaces/CameraDisplayViewInterface.swift
  14th-team5-iOS/Domain/Sources/Camera/Interfaces/CameraViewInterface.swift
  14th-team5-iOS/Domain/Sources/Camera/UseCases/CameraDisplayViewUseCase.swift
  14th-team5-iOS/Domain/Sources/Camera/UseCases/CameraViewUseCase.swift
Labels: ✨ FEATURE, 🦊 도현

#505 feat: ProfileViewController Feed 비즈니스 로직 분기 처리
  .github/workflows/swift.yml
  14th-team5-iOS/App/Sources/Presentation/Profile/Cell/CellReactor/ProfileFeedCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Dependency/ProfileFeedDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileFeedPageViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileFeedViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileFeedViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileViewReactor.swift
  14th-team5-iOS/Data/Sources/Post/PostList/DTO/PostListDTO.swift
  14th-team5-iOS/Data/Sources/Post/PostList/PostListAPI/PostListAPIWorker.swift
  14th-team5-iOS/Data/Sources/Profile/DataMapping/ProfilePostDTO.swift
  14th-team5-iOS/Data/Sources/Profile/ProfileAPI/ProfileAPIWorker.swift
  14th-team5-iOS/Data/Sources/Profile/Repositories/ProfileViewRepository.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/Colors/Black.colorset/Contents.json
  14th-team5-iOS/Domain/Sources/Post/Entities/PostListData.swift
  14th-team5-iOS/Domain/Sources/Post/Entities/PostListQuery.swift
  14th-team5-iOS/Domain/Sources/Profile/Entity/ProfilePostResponse.swift
  14th-team5-iOS/Domain/Sources/Profile/Interfaces/ProfileViewInterface.swift
  14th-team5-iOS/Domain/Sources/Profile/Parameters/ProfilePostParameter.swift
  14th-team5-iOS/Domain/Sources/Profile/UseCases/ProfileFeedUseCase.swift
  14th-team5-iOS/Domain/Sources/Profile/UseCases/ProfileViewUseCase.swift
Labels: 🦊 도현, 🛠️REACTOR

#511 fix: AccountSignInViewController KakaoLogin Open URL issue 수정
  14th-team5-iOS/Data/Sources/Service/Kakao/KakaoSignInHelper.swift
  Bibbi.xcworkspace/xcshareddata/xcschemes/Bibbi-Workspace.xcscheme
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Package+Templates.swift
Labels: 🐞 BUG, 🦊 도현

#507 feat: PostCell에 MissionView UI 구현, CalendarPostCell 추가 및 분리
  14th-team5-iOS/App/Sources/Presentation/Calendar/DataSource/CalendarPostSectionModel.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/DataSource/MonthlyCalendarSectionModel.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Dependency/CalendarPostCellDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Dependency/CalendarPostDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarPostCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarPostViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/MissionTextReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/Cell/CalendarPostCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarPostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Views/MissionTextView.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Views/PostDetailCollectionViewCell.swift
  14th-team5-iOS/Core/Sources/Extensions/UIView+Ext.swift
  14th-team5-iOS/Data/Sources/Calendar/CalendarAPI/CalendarAPIWorker.swift
  14th-team5-iOS/Data/Sources/Calendar/CalendarAPI/DataMapping/ArrayResponseDailyCalendarResponseDTO.swift
  14th-team5-iOS/Data/Sources/Calendar/Repository/CalendarRepository.swift
  14th-team5-iOS/Data/Sources/Member/Repository/MemberRepository.swift
  14th-team5-iOS/Data/Sources/Post/PostList/DTO/PostDTO.swift
  14th-team5-iOS/Data/Sources/Post/PostList/DTO/PostListDTO.swift
  14th-team5-iOS/Data/Sources/UserDefaults/FamilyUserDefautls.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/mission 1.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/mission 1.imageset/mission.svg
  14th-team5-iOS/Domain/Sources/Calendar/Entities/ArrayResponseDailyCalendarEntity.swift
  14th-team5-iOS/Domain/Sources/Calendar/Interfaces/Repositories/CalendarRepository.swift
  14th-team5-iOS/Domain/Sources/Calendar/UseCases/CalendarUseCase.swift
Labels: ✨ FEATURE, 🐼 건우

#513 refactor: Calendar 관련 코드 리팩토링, 댓글 시트 Detents 수정
  14th-team5-iOS/App/Sources/Manager/DeepLinkManager.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignIn/AccountSignInViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/ViewControllers/AccountDateViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/ViewControllers/AccountNicknameViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/ViewControllers/AccountProfileViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/ViewControllers/AccountSignUpViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/DataSource/DailyCalendarSectionModel.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Dependency/CalendarCellDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Dependency/CalendarImageCellDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Dependency/CalendarPostDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Dependency/MonthlyCalendarDIConatainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarImageCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarPageViewCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarPostCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/DailyCalendarViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/MonthlyCalendarViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/ViewModel/BannerViewModel.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/Cell/CalendarCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/Cell/CalendarImageCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/Cell/CalendarPlaceholderCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/Cell/CalendarPostCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/DailyCalendarViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/MonthlyCalendarViewController.swift
  14th-team5-iOS/App/Sources/Presentation/FamilyManagement/ViewController/FamilyManagementViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/MainFamilyViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/MainPostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/MainViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Views/MainFamilyCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Views/TimerView.swift
  14th-team5-iOS/App/Sources/Presentation/JoinFamily/ViewController/InputFamilyLinkViewController.swift
  14th-team5-iOS/App/Sources/Presentation/JoinFamily/ViewController/JoinFamilyViewController.swift
  14th-team5-iOS/App/Sources/Presentation/JoinFamily/ViewController/JoinedFamilyViewController.swift
  14th-team5-iOS/App/Sources/Presentation/OnBoarding/OnBoardingViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostComment/Dependency/CommentDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/PostComment/View/Cell/CommentCell.swift
  14th-team5-iOS/App/Sources/Presentation/PostComment/ViewController/PostCommentViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Dependency/ReactionDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Reactor/MissionTextReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Reactor/ReactionViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/PostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/ReactionMembersViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/ReactionViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/SelectableEmojiViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Views/PostDetailCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Splash/SplashViewController.swift
  14th-team5-iOS/Core/Sources/Bibbi/BibbiNavigationBarView/BibbiNavigationBarView.swift
  14th-team5-iOS/Core/Sources/Extensions/Date+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/String+Ext.swift
  14th-team5-iOS/Core/Sources/Reactive/RxUtils.swift
  14th-team5-iOS/Core/Sources/Token/TokenRepository.swift
  14th-team5-iOS/Data/Sources/Calendar/CalendarAPI/CalendarAPIWorker.swift
  14th-team5-iOS/Data/Sources/Calendar/CalendarAPI/CalendarAPIs.swift
  14th-team5-iOS/Data/Sources/Service/Apple/AppleSignInHelper.swift
  Bibbi.xcworkspace/xcshareddata/xcschemes/Bibbi-Workspace.xcscheme
Labels: 🐞 BUG, 🐼 건우, 🛠️REACTOR

#521 fix: RxAlamofire iOS Deployment Target 12.0 Settings
  Bibbi.xcworkspace/xcshareddata/xcschemes/Bibbi-Workspace.xcscheme
Labels: 🐞 BUG, 🦊 도현

#515 feat: AccountViewController Login Button Spacing or Mission API 추가
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignIn/AccountSignInViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/DailyCalendarViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Dependency/PostListsDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Reactor/PostDetailViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Reactor/PostReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Views/MissionTextView.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Views/PostDetailCollectionViewCell.swift
  14th-team5-iOS/Core/Sources/GlobalState/PostGlobalState.swift
  14th-team5-iOS/Data/Sources/Mission/DTO/MissionContentDTO.swift
  14th-team5-iOS/Data/Sources/Mission/MissionAPI/MissionAPIWorker.swift
  14th-team5-iOS/Data/Sources/Mission/MissionAPI/MissionAPIs.swift
  14th-team5-iOS/Data/Sources/Mission/Repository/MissionRepository.swift
  14th-team5-iOS/Domain/Sources/Mission/Entities/MissionContentData.swift
  14th-team5-iOS/Domain/Sources/Mission/Interfaces/MissionRepositoryProtocol.swift
  14th-team5-iOS/Domain/Sources/Mission/UseCases/GetTodayMissionUseCase.swift
  14th-team5-iOS/Domain/Sources/Mission/UseCases/MissionContentUseCase.swift
Labels: ✨ FEATURE, 🦊 도현

#522 [feat]: pickBalloonView(#519)
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/BalloonReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/MainCameraReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/MainViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/MainViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Views/BalloonView.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Views/MainCameraButtonView.swift
  14th-team5-iOS/Core/Sources/Extensions/UIStackView+Ext.swift
  14th-team5-iOS/Core/Sources/Popover/BalloonView.swift
  14th-team5-iOS/Data/Sources/View/Main/DTO/MainResponseDTO.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/polygonGray.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/polygonGray.imageset/Polygon 1.svg
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/polygonYellow.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/polygonYellow.imageset/Polygon 1 (1).svg
  14th-team5-iOS/Domain/Sources/Main/Entities/MainData.swift
  Bibbi.xcworkspace/xcshareddata/xcschemes/Bibbi-Workspace.xcscheme
  Tuist/ProjectDescriptionHelpers/Package+Templates.swift
Labels: ✨ FEATURE, 🐰 경미

#529 fix: PostDetailViewController Mission View Hidden 처리, ProfileFeedPageView Scroll Animation 추가
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Reactor/PostDetailViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Reactor/PostReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/PostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Views/PostDetailCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Dependency/ProfileFeedPageDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileFeedPageViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileFeedPageViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileFeedViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileViewReactor.swift
  14th-team5-iOS/Core/Sources/Common/Types/URLTypes.swift
  14th-team5-iOS/Core/Sources/Extensions/AVCapturePhotoOutput+Ext.swift
  14th-team5-iOS/Core/Sources/GlobalState/GlobalStateProvider.swift
  14th-team5-iOS/Core/Sources/GlobalState/ProfileFeedGlobalState.swift
  14th-team5-iOS/Core/Sources/ShareView/BibbiProfileView.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/flash.imageset/flash.svg
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/flashOff.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/flashOff.imageset/flashOff.svg
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/flashOn.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/flashOn.imageset/flashOn.svg
  Bibbi.xcworkspace/xcshareddata/xcschemes/Bibbi-Workspace.xcscheme
Labels: 🐞 BUG, ✨ FEATURE, 🦊 도현

#532 feat: KeychainWrapper, UserDefaultsWrapper 구현, Haptic 피드백 구현
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Reactor/AccountSignUpReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/ViewModel/BannerViewModel.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/BannerView.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Reactor/ReactionViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/ReactionViewController.swift
  14th-team5-iOS/Core/Sources/BBStorage/InMemoryWrapper/InMemoryStore.swift
  14th-team5-iOS/Core/Sources/BBStorage/InMemoryWrapper/InMemoryWrapper.swift
  14th-team5-iOS/Core/Sources/BBStorage/KeychainWrapper/KeychainItemAccessibility.swift
  14th-team5-iOS/Core/Sources/BBStorage/KeychainWrapper/KeychainWrapper.swift
  14th-team5-iOS/Core/Sources/BBStorage/KeychainWrapper/KeychainWrapperKey.swift
  14th-team5-iOS/Core/Sources/BBStorage/KeychainWrapper/KeychainWrapperSubscript.swift
  14th-team5-iOS/Core/Sources/BBStorage/UserDefaultsWrapper/UserDefaultsKey.swift
  14th-team5-iOS/Core/Sources/BBStorage/UserDefaultsWrapper/UserDefaultsSubscript.swift
  14th-team5-iOS/Core/Sources/BBStorage/UserDefaultsWrapper/UserDefaultsWrapper.swift
  14th-team5-iOS/Core/Sources/Modifiers/Shimmer.swift
  14th-team5-iOS/Core/Sources/Token/TokenRepository.swift
  14th-team5-iOS/Data/Sources/Account/AccountRepository/AccountRepository.swift
  14th-team5-iOS/Data/Sources/Account/MeAPI/MeAPIWorker.swift
  14th-team5-iOS/Data/Sources/Keychain/KeychainRepository.swift
  14th-team5-iOS/Domain/Sources/Main/FetchMainUseCase/FetchMainUseCaseProtocol.swift
  Bibbi.xcworkspace/contents.xcworkspacedata
  Bibbi.xcworkspace/xcshareddata/xcschemes/Bibbi-Workspace.xcscheme
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/ModuleType+Templates.swift
  Tuist/ProjectDescriptionHelpers/Package+Templates.swift
  graph.png
Labels: ✨ FEATURE, 🐼 건우

#535 fix: MainViewController segmentControl UserInteractionEnabled 처리 로직 제거
  14th-team5-iOS/App/Resources/PrivacyInfo.xcprivacy
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/MainViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/SegmentPageViewController.swift
Labels: 🦊 도현, HOTFIX
