Repository depromeet/14th-team5-iOS, pull requests merged in 2024-03, with the labels that each got.

#434 fix: 캘린더가 제대로 생성되지 못하는 문제 수정
  14th-team5-iOS/App/Project (김건우의 충돌된 사본 2024-03-01).swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarViewController.swift
  14th-team5-iOS/Core/Sources/Extensions/Date+Ext.swift
Labels: 🐼 건우, HOTFIX

#436 fix: CameraDiplayViewController 텍스트 입력 이슈 or ProfileView Feed 강제 Crash 수정
  14th-team5-iOS/App/Project.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraDisplayViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/Reactor/PrivacyViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileViewReactor.swift
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyService.swift
  14th-team5-iOS/Data/Sources/API/API.swift
Labels: 🦊 도현, HOTFIX

#439 feat: iOS Development, Distribution 타입으로 인증서 교체
  Derived/signing.keychain
  Tuist/Signing/App.DEV.mobileprovision
  Tuist/Signing/App.PRD.mobileprovision
  Tuist/Signing/App.STG.mobileprovision
  Tuist/Signing/WidgetExtension.DEV.mobileprovision
  Tuist/Signing/WidgetExtension.PRD.mobileprovision
  Tuist/Signing/WidgetExtension.STG.mobileprovision
  Tuist/Signing/dev.cer.encrypted
  Tuist/Signing/dev.p12.encrypted
  Tuist/Signing/prd.cer.encrypted
  Tuist/Signing/prd.p12.encrypted
Labels: ✨ FEATURE, 🐼 건우

#444 fix: 회원탈퇴 오류를 수정합니다.
  14th-team5-iOS/App/Sources/Presentation/Resign/AccountResignViewCotroller.swift
Labels: 🐰 경미, HOTFIX

#447 refactor : 네비게이션바 수정
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/ViewControllers/AccountNicknameViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/ViewControllers/AccountSignUpViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarPostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraDisplayViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Content/WebContentViewController.swift
  14th-team5-iOS/App/Sources/Presentation/FamilyManagement/ViewController/FamilyManagementViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/HomeViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/HomeViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostComment/ViewController/PostCommentViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/PrivacyViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileDetailViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Resign/AccountResignViewCotroller.swift
  14th-team5-iOS/Core/Sources/Base/BasePageViewController.swift
  14th-team5-iOS/Core/Sources/Base/BaseViewController.swift
  14th-team5-iOS/Core/Sources/Views/BibbiNavigationBarView/BibbiNavigationBarView.swift
  14th-team5-iOS/Core/Sources/Views/BibbiNavigationBarView/DelegateProxy/RxBibbiNavigationDelegateProxy.swift
Labels: 🐰 경미, 🛠️REACTOR

#449 fix: 의도치 않은 프로필 터치 문제 수정, 중복 Push 이벤트 문제 수정
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarPostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostComment/Reactor/CommentCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostComment/Reactor/PostCommentViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostComment/View/Cell/CommentCell.swift
  14th-team5-iOS/App/Sources/Presentation/PostComment/ViewController/PostCommentViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Reactor/PostDetailViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Reactor/PostReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/PostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Views/PostDetailCollectionViewCell.swift
  14th-team5-iOS/Core/Sources/Extensions/Notification+Ext.swift
Labels: 🐞 BUG, 🐼 건우

#450 fix: 피드의 댓글 개수가 제대로 갱신되지 않는 문제 수정
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarPostViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarPostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostComment/Reactor/PostCommentViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Reactor/ReactionViewReactor.swift
  14th-team5-iOS/Domain/Sources/Post/Entities/PostListData.swift
Labels: 🐞 BUG, 🐼 건우

#441 fix: 푸시 알림 및 위젯을 클릭하면 피드 화면으로 넘어가지 않는 문제 수정
  14th-team5-iOS/App/Sources/Application/AppDelegate.swift
  14th-team5-iOS/App/Sources/Application/SceneDelegate.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Dependency/CalendarPostDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarPostViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarPostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/HomeViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/HomeViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Dependency/PostListsDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Reactor/PostReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/PostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/ReactionViewController.swift
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyWidgetView.swift
  14th-team5-iOS/Core/Sources/App/App.swift
  14th-team5-iOS/Core/Sources/DeepLink/DeepLinkRepository.swift
  14th-team5-iOS/Core/Sources/DeepLink/Models/NotificationDeepLink.swift
  14th-team5-iOS/Core/Sources/DeepLink/Models/WidgetDeepLink.swift
  14th-team5-iOS/Core/Sources/Extensions/Date+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/DateFormatter+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/String+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UIViewController+Ext.swift
  14th-team5-iOS/Core/Sources/Member/MemberRepository.swift
  Tuist/Signing/dev.cer.encrypted
  Tuist/Signing/dev.p12.encrypted
  Tuist/Signing/prd.cer.encrypted
  Tuist/Signing/prd.p12.encrypted
Labels: ✨ FEATURE, 🐼 건우

#451 feat: PrivacyViewController Inquiry BannerView 추가
  14th-team5-iOS/App/Sources/Presentation/Privacy/PrivacyViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileViewController.swift
  14th-team5-iOS/Core/Sources/Common/URLTypes.swift
  14th-team5-iOS/Core/Sources/Extensions/UIColor+Ext.swift
  14th-team5-iOS/Core/Sources/ShareView/BibbiInquireBannerView.swift
  14th-team5-iOS/Core/Sources/ShareView/BibbiProfileView.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/Banner/airplane.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/Banner/airplane.imageset/airplane.svg
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/Banner/inquirelogo.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/Banner/inquirelogo.imageset/inquirelogo.svg
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/Colors/Blue500.colorset/Contents.json
Labels: ✨ FEATURE, 🦊 도현

#452 feat: CI github Action CI/CD 워크플로우 Setting
  .github/workflows/swift.yml
  14th-team5-iOS/App/Project.swift
  Tuist/ProjectDescriptionHelpers/Modular+Templates.swift
  Tuist/Signing/App.DEV.mobileprovision
  Tuist/Signing/App.PRD.mobileprovision
  Tuist/Signing/App.STG.mobileprovision
  Tuist/Signing/WidgetExtension.DEV.mobileprovision
  Tuist/Signing/WidgetExtension.PRD.mobileprovision
  Tuist/Signing/WidgetExtension.STG.mobileprovision
  Tuist/Signing/dev.cer.encrypted
  Tuist/Signing/dev.p12.encrypted
  Tuist/Signing/prd.cer.encrypted
  Tuist/Signing/prd.p12.encrypted
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/metadata/app_store_rating_config.json
  fastlane/metadata/copyright.txt
  fastlane/metadata/ko/apple_tv_privacy_policy.txt
  fastlane/metadata/ko/description.txt
  fastlane/metadata/ko/keywords.txt
  fastlane/metadata/ko/marketing_url.txt
  fastlane/metadata/ko/name.txt
  fastlane/metadata/ko/privacy_url.txt
  fastlane/metadata/ko/promotional_text.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/ko/subtitle.txt
  fastlane/metadata/ko/support_url.txt
  fastlane/metadata/primary_category.txt
  fastlane/metadata/primary_first_sub_category.txt
  fastlane/metadata/primary_second_sub_category.txt
  fastlane/metadata/review_information/demo_password.txt
  fastlane/metadata/review_information/demo_user.txt
  fastlane/metadata/review_information/email_address.txt
  fastlane/metadata/review_information/first_name.txt
  fastlane/metadata/review_information/last_name.txt
  fastlane/metadata/review_information/notes.txt
  fastlane/metadata/review_information/phone_number.txt
  fastlane/metadata/secondary_category.txt
  fastlane/metadata/secondary_first_sub_category.txt
  fastlane/metadata/secondary_second_sub_category.txt
  fastlane/screenshots/README.txt
Labels: ⚒️ SETTING, ✨ FEATURE, 🦊 도현

#454 feat: WillCapturePhotoFor Method 추가 및 무음 카메라 기능 추가
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraViewController.swift
Labels: ✨ FEATURE, 🦊 도현

#457 feat: 뷰에 따라 댓글시트 Detents를 달리하도록 수정
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarPostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/PostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/ReactionViewController.swift
  14th-team5-iOS/Core/Sources/Extensions/UIViewController+Ext.swift
Labels: ✨ FEATURE, 🐼 건우

#460 fix: Tuist CFBundleShortVersionString 수정 및 gitHub action CI/CD 수정
  .github/workflows/swift.yml
  14th-team5-iOS/App/Project.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraViewController.swift
  fastlane/Fastfile
  fastlane/README.md
Labels: ⚒️ SETTING, 🦊 도현

#464 feat: 이모지 간격 수정(#463)
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/ReactionViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Views/ReactionCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Views/RightAlignedFlowLayout.swift
Labels: ✨ FEATURE
