Repository depromeet/14th-team5-iOS, pull requests merged in 2024-09, with the labels that each got.

#634 fix: 댓글 화면에서 알 수 없는 사용자 프로필로 이동하는 문제 수정
  14th-team5-iOS/App/Sources/Presentation/Comment/Reactor/Cell/CommentCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Comment/ViewController/CommentViewController.swift
  14th-team5-iOS/Data/Sources/APIs/My/Repository/MyRepository.swift
  14th-team5-iOS/Domain/Sources/UseCases/My/CheckIsVaildMemberUseCase.swift
Labels: 🐞 BUG, 🐼 건우

#639 feat: BBToolTip View UI 추가 해요
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignIn/AccountSignInReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignIn/AccountSignInViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Reactor/AccountSignUpReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/MainViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Resign/Reactor/AccountResignViewReactor.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToolTip/BBAnimatable.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToolTip/BBDrawable.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToolTip/BBToolTipConfiguration.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToolTip/BBToolTipPosition.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToolTip/BBToolTipType.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToolTip/BBToolTipView.swift
  14th-team5-iOS/Data/Sources/APIs/My/Repository/MyRepository.swift
  14th-team5-iOS/Data/Sources/Storages/UserDefaults/AppUserDefaults/AppUserDefaults.swift
  14th-team5-iOS/Domain/Sources/Repositories/MyRepository.swift
  14th-team5-iOS/Domain/Sources/UseCases/My/FetchIsFirstOnboardingUseCase.swift
  14th-team5-iOS/Domain/Sources/UseCases/My/UpdateIsFirstOnboardingUseCase.swift
Labels: ✨ FEATURE, 🦊 도현

#638 feat: BBAlert에 BBAlertAction 구현, BBAlert 문서 주석 추가
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/AlertViews/BBAlertView.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/AlertViews/DefaultToastView/DefaultAlertView.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/BBAlert.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/BBAlertAction.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/BBAlertActionStyle.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/BBAlertAnimation.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/BBAlertBackground.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/BBAlertButton.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/BBAlertButtonsAxis.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/BBAlertConfiguration.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/BBAlertDelegate.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/BBAlertStyle.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/BBAlertViewConfiguration.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/ButtonLayout.swift
  14th-team5-iOS/Core/Sources/Trash/Popover/BibbiPopOverView.swift
  14th-team5-iOS/Core/Sources/Trash/Popover/DescriptionPopoverViewController.swift
Labels: ✨ FEATURE, 🐼 건우

#642 docs: Pull Request 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 DOCS, 🐼 건우

#640 feat: BBAlertService구현, Pick 로직이 제대로 이뤄지지 못하는 문제 수정
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/Cell/MainFamilyCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/MainViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Views/MainFamilyCollectionViewCell.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBServices/BBAlertService.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBServices/ServiceProvider.swift
Labels: ✨ FEATURE, 🐼 건우

#643 refactor: Wrapper 클래스에 @Wrapper 매크로 적용
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Calendar/DailyCalendarViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Calendar/MonthlyCalendarViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Camera/CameraDisplayViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Camera/CameraViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Comment/CommentViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/JoinFamily/FamilyEntranceControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/JoinFamily/FamilyNameSettingViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/JoinFamily/InputFamilyLinkViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/JoinFamily/JoinFamilyViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Main/MainFamilyViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Main/MainPostViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Main/MainViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Management/FamilyNameSettingViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Management/ManagementViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Onboarding/OnboardingViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/PostDetail/PostDetailViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/PostDetail/ReactionMembersViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/PostDetail/ReactionViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/PostDetail/SelectableEmojiViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Privacy/PrivacyViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Profile/ProfileDetailViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Profile/ProfileFeedPageViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Profile/ProfileFeedViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Profile/ProfileViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Resign/AccountResignViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/SignIn/SignInViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/Splash/SplashViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/WebContent/WebContentViewControllerWrapper.swift
  14th-team5-iOS/Core/Sources/Base/BaseWrapper.swift
Labels: 🐼 건우, 🛠️REACTOR

#658 fix: 프로필 미션 피드 불러오기 기능 수정 및 기타 이슈 반영
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileFeedViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileFeedViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileViewReactor.swift
  14th-team5-iOS/Core/Sources/Base/BaseTableView.swift
  14th-team5-iOS/Core/Sources/Base/BaseViewController.swift
  14th-team5-iOS/Core/Sources/Base/ReactorViewController.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBServices/ProfileGlobalState.swift
Labels: 🐞 BUG, 🦊 도현

#646 feat: BBToastService 구현, BBToast의 버튼 액션이 전달되지 않는 문제 수정
  14th-team5-iOS/App/Sources/Application/Navigator/ManagementNavigator.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/MainViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Management/Activity/CopyInvitationUrlActivity.swift
  14th-team5-iOS/App/Sources/Presentation/Management/Reactor/ManagementReactor.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/BBAlertAnimation.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/BBAlertBackground.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBButton/BBButton.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/BBToast.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/BBToastAnimation.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/BBToastBackground.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/BBToastConfiguration.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/BBToastDelegate.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/BBToastDirection.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/BBToastDismissable.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/BBToastViewConfiguration.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/ToastViews/DefaultToastView/ButtonToastView.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/ToastViews/DefaultToastView/DefaultToastView.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/ToastViews/DefaultToastView/IconToastView.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBServices/BBToastService.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBServices/ServiceProvider.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBServices/ToastMessageGlobalState.swift
Labels: ✨ FEATURE, 🐼 건우

#656 fix: 댓글 이미지 둥글기 반경 수정 등
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarPostCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/MonthlyCalendarViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/View/Cell/CalendarPostCell.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/MonthlyCalendarViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Comment/View/Cell/CommentCell.swift
Labels: 🐞 BUG, 🐼 건우

#661 feat: 카메라 화면 BBToast 기능 추가
  14th-team5-iOS/App/Sources/Application/DIContainer/NavigatorDIContainer.swift
  14th-team5-iOS/App/Sources/Application/Navigator/CameraDisplayNavigator.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraDisplayViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraDisplayViewReactor.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/BBToastConfiguration.swift
Labels: ✨ FEATURE, 🦊 도현

#660 fix: Pick 액션 후 Toast가 출력되지 않는 문제 수정
  14th-team5-iOS/App/Sources/Presentation/Comment/Reactor/CommentViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Comment/ViewController/CommentViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/Cell/MainFamilyCellReactor.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/BBToastConfiguration.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/BBToastDirection.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/ToastViews/DefaultToastView/ButtonToastView.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/ToastViews/DefaultToastView/DefaultToastView.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBToast/ToastViews/DefaultToastView/IconToastView.swift
Labels: 🐞 BUG, 🐼 건우

#667 feat: 가족 정보를 유저디펄트에 저장해요
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBButton/BBButton.swift
  14th-team5-iOS/Data/Sources/APIs/Family/Repository/FamilyRepository.swift
  14th-team5-iOS/Data/Sources/APIs/MainView/MainViewAPI/MainViewAPIWorker.swift
  14th-team5-iOS/Data/Sources/APIs/MainView/Repository/MainViewRepository.swift
  14th-team5-iOS/Domain/Sources/UseCases/Post/FetchPostListUseCase.swift
Labels: ✨ FEATURE

#665 fix: 로그인 시 메인화면 진입 못하는 이슈 수정해요
  14th-team5-iOS/App/Sources/Application/Navigator/AccountSignInNavigator.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignIn/AccountSignInReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignIn/AccountSignInViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/MainViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/OnBoarding/OnBoardingReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Resign/Reactor/AccountResignViewReactor.swift
  14th-team5-iOS/Data/Sources/APIs/My/Repository/MyRepository.swift
  14th-team5-iOS/Data/Sources/Storages/UserDefaults/AppUserDefaults/AppUserDefaults.swift
  14th-team5-iOS/Domain/Sources/UseCases/My/FetchIsFirstOnboardingUseCase.swift
  14th-team5-iOS/Domain/Sources/UseCases/My/UpdateIsFirstOnboardingUseCase.swift
Labels: 🐞 BUG, 🦊 도현
