Repository depromeet/14th-team5-iOS, pull requests merged in 2024-10, with the labels that each got.

#672 fix: 가족방 이름 설정화면 레이아웃 및 카메라 텍스트 정렬 이슈 수정해요
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraDisplayViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraDisplayViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/View/BibbiMissionView.swift
  14th-team5-iOS/App/Sources/Presentation/Content/WebContentViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Management/ViewController/FamilyNameSettingViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/View/BibbiInquireBannerView.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/View/BibbiProfileView.swift
  14th-team5-iOS/App/Sources/Presentation/Resign/View/BibbiCheckBoxView.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBServices/ProfileFeedGlobalState.swift
  14th-team5-iOS/Core/Sources/URLTypes.swift
Labels: 🐞 BUG, 🦊 도현

#654 feat: BBAPISpec, BBAPIWorker, BBNetworkService 등 BBNetowrk 모듈 구현
  14th-team5-iOS/App/Sources/Application/AppDelegate.swift
  14th-team5-iOS/App/Sources/Presentation/Comment/Reactor/CommentViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Comment/ViewController/CommentViewController.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBErrorLogger.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/BBAPIErrorLogger.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/BBAPIErrorMapper.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/BBAPISpec.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/BBAPIWorker.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/BBNetworkConfiguration.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/BBNetworkError.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/BBNetworkErrorLogger.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/BBNetworkEventMonitor.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/BBNetworkInterceptor.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/BBNetworkService.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/BBNetworkSessionManager.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/Components/BBNetworkHeader.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/Components/BBNetworkMethod.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/Components/BBNetworkParameter.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Utils/BBBodyEncoder.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Utils/BBResponseDecoder.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBStorages/KeychainWrapper/KeychainWrapper.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBStorages/KeychainWrapper/KeychainWrapperSubscript.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBStorages/UserDefaultsWrapper/Models/AuthToken.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBStorages/UserDefaultsWrapper/UserDefaultsWrapper.swift
  14th-team5-iOS/Core/Sources/Extensions/Bundle+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/Data+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/Encodable+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/Modifiers/Shimmer.swift
  14th-team5-iOS/Core/Sources/Extensions/ObservableType+Ext.swift
  14th-team5-iOS/Core/Sources/Trash/BBNetwork/API.swift
  14th-team5-iOS/Core/Sources/Trash/BBNetwork/APIConfig.swift
  14th-team5-iOS/Core/Sources/Trash/BBNetwork/APISpec.swift
  14th-team5-iOS/Core/Sources/Trash/BBRx/Repositories/Token/TokenRepository.swift
  14th-team5-iOS/Core/Sources/Utils/Haptic.swift
  14th-team5-iOS/Core/Sources/Utils/Mixpanel/MixPanelService+Account.swift
  14th-team5-iOS/Core/Sources/Utils/Mixpanel/MixPanelService+Camera.swift
  14th-team5-iOS/Core/Sources/Utils/Mixpanel/MixPanelService+Family.swift
  14th-team5-iOS/Core/Sources/Utils/Mixpanel/MixPanelService+Home.swift
  14th-team5-iOS/Core/Sources/Utils/Mixpanel/MixpanelService.swift
  14th-team5-iOS/Core/Sources/Utils/MulticastDelegate.swift
  14th-team5-iOS/Core/Sources/Utils/Reactive/RxInterval.swift
  14th-team5-iOS/Core/Sources/Utils/Reactive/RxObject.swift
  14th-team5-iOS/Core/Sources/Utils/Reactive/RxScheduler.swift
  14th-team5-iOS/Data/Sources/APIs/Comment/CommentAPI/CommentAPIWorker.swift
  14th-team5-iOS/Data/Sources/APIs/Comment/CommentAPI/CommentAPIs.swift
  14th-team5-iOS/Data/Sources/APIs/Comment/Repository/CommentRepository.swift
  14th-team5-iOS/Data/Sources/APIs/OAuth/OAuthAPI/Repository/OAuthRepository.swift
  14th-team5-iOS/Data/Sources/Storages/Keychain/TokenKeychain/Models/OldAccessToken.swift
  14th-team5-iOS/Data/Sources/Storages/Keychain/TokenKeychain/TokenKeychain.swift
  14th-team5-iOS/Data/Sources/Trash/APIWorker.swift
  14th-team5-iOS/Data/Sources/Trash/BibbiNetworkMonitor.swift
  14th-team5-iOS/Data/Sources/Trash/NetworkIntercepter.swift
  14th-team5-iOS/Domain/Sources/Repositories/CommentRepository.swift
  14th-team5-iOS/Domain/Sources/Trash/PostComment/UseCase/PostCommentUseCase.swift
  14th-team5-iOS/Domain/Sources/UseCases/Comment/FetchCommentUseCase.swift
Labels: ✨ FEATURE, 🐼 건우

#674 fix: 가족 이름이 공백으로 뜨는 문제 수정
  14th-team5-iOS/App/Sources/Presentation/Management/Reactor/FamilyNameSettingViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Management/Reactor/ManagementReactor.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/BBAPIWorker.swift
  14th-team5-iOS/Data/Sources/APIs/Family/FamilyAPI/DataMapping/FamilyGroupInfoResponseDTO.swift
  14th-team5-iOS/Domain/Sources/Entities/Family/FamilyGroupInfoEntity.swift
Labels: 🐞 BUG, 🐼 건우

#676 fix: BBAlert 버튼 패딩 수정
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/AlertViews/DefaultToastView/DefaultAlertView.swift
Labels: 🐞 BUG, 🐼 건우

#681 feat: BibbiNetworkMonitor Legacy 코드 제거
  14th-team5-iOS/App/Project.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/BBNetworkEventMonitor.swift
  14th-team5-iOS/Core/Sources/Utils/Logger/BBLogger.swift
  14th-team5-iOS/Data/Sources/Trash/APIWorker.swift
  14th-team5-iOS/Data/Sources/Trash/BibbiNetworkMonitor.swift
  Tuist/ProjectDescriptionHelpers/Modular+Templates.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  fastlane/Fastfile
Labels: ⚒️ SETTING, ✨ FEATURE, 🦊 도현

#679 fix: Home에서 발생한 이슈들을 수정해요.
  14th-team5-iOS/App/Sources/Application/DIContainer/AppDIContainer.swift
  14th-team5-iOS/App/Sources/Application/DIContainer/NavigatorDIContainer.swift
  14th-team5-iOS/App/Sources/Application/Navigator/InputFamilyLinkNavigator.swift
  14th-team5-iOS/App/Sources/Application/Navigator/MainNavigator.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/FamilyEntrance/FamilyEntranceControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/FamilyEntrance/InputFamilyLinkViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Application/Navigator/Wrapper/FamilyEntrance/JoinFamilyViewControllerWrapper.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignIn/AccountSignInViewController.swift
  14th-team5-iOS/App/Sources/Presentation/FamilyEntrance/Reactor/InputFamilyLinkReactor.swift
  14th-team5-iOS/App/Sources/Presentation/FamilyEntrance/ViewController/InputFamilyLinkViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/MainViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/MainViewController.swift
  14th-team5-iOS/Data/Sources/APIs/App/Repository/AppRepository.swift
  14th-team5-iOS/Data/Sources/Storages/UserDefaults/AppUserDefaults/AppUserDefaults.swift
  14th-team5-iOS/Domain/Sources/Repositories/AppRepository.swift
  14th-team5-iOS/Domain/Sources/UseCases/App/FetchFamilyManagementUseCase.swift
  14th-team5-iOS/Domain/Sources/UseCases/App/IsFirstWidgetAlertUseCase.swift
  14th-team5-iOS/Domain/Sources/UseCases/App/SaveIsFirstFamilyManagementUseCase.swift
  14th-team5-iOS/Domain/Sources/UseCases/App/SaveIsFirstWidgetAlertUseCase.swift
  14th-team5-iOS/Domain/Sources/UseCases/MainView/CheckSurvivalTimeUseCase.swift
Labels: HOTFIX

#685 chore: github Action 브런치 제약구문 제거 및 코드 간소화
  .github/workflows/swift.yml
Labels: ⚒️ SETTING, 🦊 도현

#687 fix: github Action Pull Reqeust Closed시 Action 실행하도록 수정해요
  .github/workflows/swift.yml
Labels: ⚒️ SETTING, 🦊 도현

#689 fix: FastLane buildNumber Method 수정
  fastlane/Fastfile
Labels: 🐞 BUG, 🦊 도현

#692 feat: AlertService 구현
  14th-team5-iOS/Core/Sources/Bibbi/BBHelper.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBServices/AlertService.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBServices/PostGlobalState.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBServices/ProfileGlobalState.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBServices/ServiceProvider.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBServices/ToastMessageGlobalState.swift
Labels: ✨ FEATURE, 🐼 건우
