Repository depromeet/14th-team5-iOS, pull requests merged in 2024-02, with the labels that each got.

#360 hotfix: 홈 피드 화면, 위젯 사진 돌아가는 이슈 해결
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/HomeViewReactor.swift
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyWidgetView.swift
Labels: 🐭 건희, HOTFIX

#364 fix:타이머 수정
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/HomeViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: 🐰 경미, HOTFIX

#362 refactor: Date↔String 변환 로직 수정
  14th-team5-iOS/Core/Sources/Extensions/Date+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/DateFormatter+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/String+Ext.swift
  14th-team5-iOS/Data/Sources/Calendar/CalendarAPI/DataMapping/BannerResponseDTO.swift
Labels: 🐼 건우, 🛠️REACTOR

#366 fix: PrivacyTableViewCell, AuthorizationCell image 수정 및 ContentMode 변경
  14th-team5-iOS/App/Project.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/Cell/PrivacyAuthorizationTableViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/Cell/PrivacyTableViewCell.swift
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyWidgetView.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/settingArrow.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/settingArrow.imageset/settingArrow.svg
Labels: 🦊 도현, HOTFIX

#370 fix: camera zoom in zoom out Button Action 추가 및 ReactionMemberViewController Emoji Type추가
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Dependency/ReactionDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Dependency/ReactionMemberDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Reactor/PostReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Reactor/ReactionMemberReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Reactor/TempReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/PostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/ReactionMembersViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/ReactionViewController.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/zoomin.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/zoomin.imageset/zoomin.svg
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/zoomout.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/zoomout.imageset/zoomout.svg
Labels: 🦊 도현, HOTFIX

#372 feat: info.plist에 LaunchScreen.storyboard 파일 적용
  14th-team5-iOS/App/Project.swift
Labels: ⚒️ SETTING, 🐼 건우

#387 Profile 기본 이미지 로직 수정 및 Profile 이미지 삭제 API 추가
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Reactor/AccountSignUpReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/ViewControllers/AccountNicknameViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/ViewControllers/AccountProfileViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraDisplayViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraDisplayViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/HomeViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileViewReactor.swift
  14th-team5-iOS/Core/Sources/Extensions/Date+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/Notification+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UIViewController+Ext.swift
  14th-team5-iOS/Core/Sources/ShareView/BibbiProfileView.swift
  14th-team5-iOS/Core/Sources/Views/BibbiToast/BibbiToastMessageView.swift
  14th-team5-iOS/Data/Sources/Profile/ProfileAPI/ProfileAPIWorker.swift
  14th-team5-iOS/Data/Sources/Profile/ProfileAPI/ProfileAPIs.swift
  14th-team5-iOS/Data/Sources/Profile/Repositories/ProfileViewRepository.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/arrow_yellow_right.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/arrow_yellow_right.imageset/arrow_yellow_right.svg
  14th-team5-iOS/Domain/Sources/Account/DataMapping/AccountNickNameEditDTO.swift
  14th-team5-iOS/Domain/Sources/Account/Entity/AccountNickNameEditResponse.swift
  14th-team5-iOS/Domain/Sources/Profile/Interfaces/ProfileViewInterface.swift
  14th-team5-iOS/Domain/Sources/Profile/UseCases/ProfileViewUseCase.swift
Labels: 🐞 BUG, 🦊 도현

#390 feat: SettingViewController Version issue 수정 및 Profile Nickname 영역 수정
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraDisplayViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/PrivacyViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Dependency/ProfileDetailDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileDetailViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileDetailViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Resign/Reactor/AccountResignViewReactor.swift
  14th-team5-iOS/Core/Sources/Extensions/Bundle+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UIImage+Ext.swift
  14th-team5-iOS/Core/Sources/ShareView/BibbiProfileView.swift
  14th-team5-iOS/Data/Sources/API/API.swift
  14th-team5-iOS/Domain/Sources/Privacy/Privacy.swift
Labels: ✨ FEATURE, 🦊 도현

#393 feat: 강제 업데이트 팝업 표출
  14th-team5-iOS/App/Sources/Presentation/Splash/SplashReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Splash/SplashViewController.swift
  14th-team5-iOS/Core/Sources/Extensions/Notification+Ext.swift
  14th-team5-iOS/Data/Sources/API/APIWorker.swift
  14th-team5-iOS/Data/Sources/Account/AccountAPI/AccountAPIWorker.swift
  14th-team5-iOS/Data/Sources/Account/MeAPI/MeAPIWorker.swift
  14th-team5-iOS/Data/Sources/Account/MeAPI/MeAPIs.swift
  14th-team5-iOS/Domain/Sources/AppVersion.swift
  14th-team5-iOS/Domain/Sources/Me/MeRepositoryProtocol.swift
  14th-team5-iOS/Domain/Sources/Me/MeUseCase.swift
Labels: ✨ FEATURE, 🐭 건희

#395 feat: 위젯 문구수정 로직 추가
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/TimerReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Views/TimerView.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/widget.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/widget.imageset/widget.svg
  Bibbi.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: ✨ FEATURE, 🐭 건희

#396 fix: 프로필 수정 후 가족 초대 화면에 변경 사항이 반영되지 않는 문제 수정
  14th-team5-iOS/App/Sources/Presentation/FamilyManagement/Reactor/FamilyManagementViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Dependency/ProfileDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileViewReactor.swift
  14th-team5-iOS/Core/Sources/GlobalState/GlobalStateProvider.swift
  14th-team5-iOS/Core/Sources/GlobalState/ProfileGlobalState.swift
Labels: 🐞 BUG, 🐼 건우

#399 feat: ProfileView Feed UI figma 수정 사항 반영
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraDisplayViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Cell/CellReactor/ProfileFeedCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Cell/CellReactor/ProfileFeedDescrptionCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Cell/ProfileFeedCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Cell/ProfileFeedDescrptionCell.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/DataSources/ProfileFeedDescrptionSectionModel.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileViewReactor.swift
  14th-team5-iOS/Core/Sources/Extensions/UIFont+Ext.swift
Labels: ✨ FEATURE, 🦊 도현

#401 fix: Camera RealEmoji Image 잘림 issue 수정
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Cell/BibbiRealEmojiViewCell.swift
Labels: ✨ FEATURE, 🦊 도현

#402 feat: 피드 및 댓글 푸시 딥링크 기능 구현
  14th-team5-iOS/App/Sources/Application/AppDelegate.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarPostViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/ImageCalendarCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/Strings/CalenderStrings.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarPostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/PostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/ReactionViewController.swift
  14th-team5-iOS/Core/Sources/GlobalState/ToastMessageGlobalState.swift
  14th-team5-iOS/Core/Sources/Member/MemberRepository.swift
Labels: ✨ FEATURE, 🐼 건우

#411 fix: App 버전에 따른 강제업데이트 팝업 표출 항목 버그 수정
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/HomeViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/PostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Splash/SplashReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Splash/SplashViewController.swift
  14th-team5-iOS/Data/Sources/API/APIWorker.swift
  14th-team5-iOS/Data/Sources/Account/MeAPI/MeAPIWorker.swift
  14th-team5-iOS/Data/Sources/Service/AccountSignInHelper.swift
  14th-team5-iOS/Data/Sources/Service/Kakao/KakaoSignInHelper.swift
Labels: 🐞 BUG, 🐭 건희

#413 feat: PostDetailView 화면에서 CameraViewController 화면 전환 로직 수정
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Dependency/CameraDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/PostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/SelectableEmojiViewController.swift
  Bibbi.xcworkspace/contents.xcworkspacedata
Labels: ✨ FEATURE, 🦊 도현

#419 Fix/#415 fix accesstoken refreshtoken 모두 만료 됐을 때 로직 추가
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignIn/AccountSignInViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/Reactor/PrivacyViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Splash/SplashViewController.swift
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyService.swift
  14th-team5-iOS/Data/Sources/API/API.swift
  14th-team5-iOS/Data/Sources/API/APIWorker.swift
  14th-team5-iOS/Data/Sources/Account/AccountAPI/AccountAPIWorker.swift
Labels: 🐞 BUG, ✨ FEATURE, 🐭 건희

#420 feat: 가족 생성 날짜 API 호출 로직 구현, 캘린더 생성 로직 수정
  14th-team5-iOS/App/Sources/Presentation/Calendar/Reactor/CalendarViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarPostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Calendar/ViewController/CalendarViewController.swift
  14th-team5-iOS/App/Sources/Presentation/JoinFamily/Reactor/InputFamilyLinkReactor.swift
  14th-team5-iOS/App/Sources/Presentation/JoinFamily/Reactor/JoinFamilyReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Splash/Dependency/SplashDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Splash/SplashReactor.swift
  14th-team5-iOS/Core/Sources/Extensions/Date+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/DateFormatter+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/Reactive+Ext.swift
  14th-team5-iOS/Data/Sources/Family/FamilyAPI/DataMapping/JoinFamilyResponseDTO.swift
  14th-team5-iOS/Data/Sources/Family/Repository/FamilyRepository.swift
  14th-team5-iOS/Domain/Sources/Family/Entities/JoinFamilyResponse.swift
  14th-team5-iOS/Domain/Sources/Family/Interfaces/Repositories/FamilyRepository.swift
  14th-team5-iOS/Domain/Sources/Family/UseCases/FamilyUseCase.swift
Labels: ✨ FEATURE, 🐼 건우

#423 fix: 로그아웃시 FCM 삭제 로직 수정
  14th-team5-iOS/App/Sources/Application/AppDelegate.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignIn/AccountSignInDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignIn/AccountSignInReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Dependency/HomeDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/HomeViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/HomeViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/Dependency/PrivacyDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/Reactor/PrivacyViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Resign/AccountResignViewCotroller.swift
  14th-team5-iOS/App/Sources/Presentation/Resign/Reactor/AccountResignViewReactor.swift
  14th-team5-iOS/Core/Sources/Token/TokenRepository.swift
  14th-team5-iOS/Data/Sources/API/VoidResponse.swift
  14th-team5-iOS/Data/Sources/Account/AccountRepository/AccountRepository.swift
  14th-team5-iOS/Data/Sources/Account/MeAPI/MeAPIWorker.swift
  14th-team5-iOS/Data/Sources/Keychain/KeychainRepository.swift
  14th-team5-iOS/Data/Sources/Resign/Repositories/AccountResignViewRepository.swift
  14th-team5-iOS/Data/Sources/Resign/ResignAPI/ResignAPIWorker.swift
  14th-team5-iOS/Data/Sources/UserDefaults/FamilyUserDefautls.swift
  14th-team5-iOS/Data/Sources/UserDefaults/UserDefaultsRepository.swift
  14th-team5-iOS/Domain/Sources/Account/AccessToken.swift
  14th-team5-iOS/Domain/Sources/FCM/Entities/FCMToken.swift
  14th-team5-iOS/Domain/Sources/FCM/UseCases/FCMUseCase.swift
  14th-team5-iOS/Domain/Sources/Interfaces/FCMRepositoryProtocol.swift
  14th-team5-iOS/Domain/Sources/Interfaces/KeychainRepositoryProtocol.swift
  14th-team5-iOS/Domain/Sources/Interfaces/UserDefaultsRepositoryProtocol.swift
  14th-team5-iOS/Domain/Sources/Post/Entities/EmojiData.swift
  14th-team5-iOS/Domain/Sources/Post/Entities/PostData.swift
  14th-team5-iOS/Domain/Sources/Post/Entities/PostListData.swift
  14th-team5-iOS/Domain/Sources/Post/Entities/PostListQuery.swift
  14th-team5-iOS/Domain/Sources/Post/Entities/PostQuery.swift
  14th-team5-iOS/Domain/Sources/Post/Interfaces/PostListRepositoryProtocol.swift
  14th-team5-iOS/Domain/Sources/Post/UseCases/PostListUseCase.swift
  14th-team5-iOS/Domain/Sources/Resign/Interfaces/AccountResignInterface.swift
  14th-team5-iOS/Domain/Sources/Resign/UseCases/AccountResignUseCase.swift
  14th-team5-iOS/Domain/Sources/SignOut/UseCases/SignOutUseCase.swift
Labels: 🐞 BUG, ✨ FEATURE, 🐰 경미

#426 feat: 홈과 피드에서 발생하는 2.5차 QA 수정하였습니다.
  14th-team5-iOS/App/Sources/Presentation/Home/Model/String/HomeCGFloat.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/HomeViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/HomeViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/ReactionViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Views/AddCommentCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Views/AddReactionCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Views/ReactionCollectionViewCell.swift
Labels: ✨ FEATURE, 🐰 경미

#427 Profile Feed Cell Text 잘림 현상 및 이미지 업로드 실패 예외 처리 로직 추가
  .tuist-version
  14th-team5-iOS/App/Project.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraDisplayViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Cell/BibbiRealEmojiViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Cell/CellReactor/BibbiRealEmojiCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Cell/DisplayEditCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Dependency/CameraDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraDisplayViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/PostViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/ViewControllers/SelectableEmojiViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Cell/ProfileFeedCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Cell/ProfileFeedDescrptionCell.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileViewController.swift
  14th-team5-iOS/Core/Sources/Extensions/UIImage+Ext.swift
  14th-team5-iOS/Data/Sources/Camera/CameraAPI/CameraAPIWorker.swift
  14th-team5-iOS/Data/Sources/Camera/DataMapping/CameraDisplayImageDTO.swift
  14th-team5-iOS/Data/Sources/Camera/DataMapping/CameraRealEmojiImageItemDTO.swift
  14th-team5-iOS/Data/Sources/Camera/Repositories/CameraDisplayViewRepository.swift
  14th-team5-iOS/Data/Sources/Camera/Repositories/CameraViewRepository.swift
  14th-team5-iOS/Domain/Sources/Camera/Entity/CameraRealEmojiImageItemResponse.swift
  14th-team5-iOS/Domain/Sources/Camera/Interfaces/CameraDisplayViewInterface.swift
  14th-team5-iOS/Domain/Sources/Camera/Interfaces/CameraViewInterface.swift
  14th-team5-iOS/Domain/Sources/Camera/Parameters/CameraDisplayPostParameters.swift
  14th-team5-iOS/Domain/Sources/Camera/UseCases/CameraDisplayViewUseCase.swift
  14th-team5-iOS/Domain/Sources/Camera/UseCases/CameraViewUseCase.swift
  Bibbi.xcworkspace/contents.xcworkspacedata
  Bibbi.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Tuist/ProjectDescriptionHelpers/Modular+Templates.swift
Labels: 🐞 BUG, 🦊 도현

#431 feat: 홈에서 글 내용 삭제(#430)
  14th-team5-iOS/App/Sources/Presentation/Home/Views/FeedCollectionViewCell.swift
Labels: ✨ FEATURE, 🐰 경미

#429 fix: Tuist CFBundleShortVersionString 1.1.6 수정
  14th-team5-iOS/App/Project.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/CameraDisplayViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Views/AddCommentCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Privacy/Reactor/PrivacyViewReactor.swift
  14th-team5-iOS/App/WidgetExtension/Sources/FamilyWidget/FamilyService.swift
  14th-team5-iOS/Data/Sources/API/API.swift
Labels: ✨ FEATURE, 🦊 도현
