Repository depromeet/14th-team5-iOS, pull requests merged in 2024-11, with the labels that each got.

#697 fix: QA 중 나온 오류 사항을 수정합니다.
  14th-team5-iOS/App/Sources/Presentation/Account/AccountSignUp/Reactor/AccountSignUpReactor.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBAlert/BBAlert.swift
Labels: HOTFIX

#695 fix: 로그인 버튼 클릭시 touch event cancel 현상 수정해요
  14th-team5-iOS/App/Project.swift
  14th-team5-iOS/App/Sources/Presentation/Splash/SplashReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Splash/SplashViewController.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBCommons/BBButton/BBButton.swift
  14th-team5-iOS/Core/Sources/Extensions/Bundle+Ext.swift
  14th-team5-iOS/Core/Sources/Trash/BBNetwork/API.swift
  14th-team5-iOS/Data/Sources/Storages/UserDefaults/FamilyUserDefaults/FamilyUserDefaults.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 🐞 BUG, 🦊 도현

#700 fix: ResignAPI 호출 시 UserDefaults MemberId nil 값 뜨는 이슈 수정해요
  14th-team5-iOS/Data/Sources/Storages/UserDefaults/MyUserDefaults/MyUserDefaults.swift
Labels: 🐞 BUG, 🦊 도현

#707 refactor: PostAPIWorker 기존 Network 모듈 리팩토링
  14th-team5-iOS/Data/Sources/Trash/Post/PostList/DataMapping/CreatePostRequestDTO.swift
  14th-team5-iOS/Data/Sources/Trash/Post/PostList/DataMapping/CreatePresignedURLRequestDTO.swift
  14th-team5-iOS/Data/Sources/Trash/Post/PostList/DataMapping/PostDetailResponseDTO.swift
  14th-team5-iOS/Data/Sources/Trash/Post/PostList/DataMapping/PostListQueryDTO.swift
  14th-team5-iOS/Data/Sources/Trash/Post/PostList/DataMapping/PostListRequestDTO.swift
  14th-team5-iOS/Data/Sources/Trash/Post/PostList/DataMapping/PostRequestDTO.swift
  14th-team5-iOS/Data/Sources/Trash/Post/PostList/DataMapping/PostResponseDTO.swift
  14th-team5-iOS/Data/Sources/Trash/Post/PostList/PostAPI/PostAPIs.swift
  14th-team5-iOS/Data/Sources/Trash/Post/PostList/PostAPI/PostListAPIWorker.swift
  14th-team5-iOS/Data/Sources/Trash/Post/PostList/Repository/PostRepository.swift
  14th-team5-iOS/Domain/Sources/Entities/PostList/CreatePostPresignedURLRequest.swift
  14th-team5-iOS/Domain/Sources/Entities/PostList/CreatePostQuery.swift
  14th-team5-iOS/Domain/Sources/Entities/PostList/CreatePostRequest.swift
  14th-team5-iOS/Domain/Sources/Entities/PostList/PostDetailEntity.swift
  14th-team5-iOS/Domain/Sources/Repositories/PostListRepository.swift
  14th-team5-iOS/Domain/Sources/UseCases/Members/FetchMembersPostListUseCase.swift
  14th-team5-iOS/Domain/Sources/UseCases/Post/FetchPostListUseCase.swift
Labels: 🦊 도현, 🛠️REACTOR

#705 refactor: CameraAPIWorker 기존 Network 모듈 리펙토링
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraDisplayViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Camera/Reactor/CameraViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileViewReactor.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/BBAPIWorker.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/BBNetworkService.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/BBNetworkSessionManager.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Utils/BBUploadResponseSerializer.swift
  14th-team5-iOS/Data/Sources/APIs/Camera/CameraAPIWorker.swift
  14th-team5-iOS/Data/Sources/APIs/Camera/CameraAPIs.swift
  14th-team5-iOS/Data/Sources/APIs/Camera/DataMapping/CameraCreateRealEmojiResponseDTO.swift
  14th-team5-iOS/Data/Sources/APIs/Camera/DataMapping/CameraDisplayImageResponseDTO.swift
  14th-team5-iOS/Data/Sources/APIs/Camera/DataMapping/CameraDisplayPostResponseDTO.swift
  14th-team5-iOS/Data/Sources/APIs/Camera/DataMapping/CameraRealEmojiImageItemResponseDTO.swift
  14th-team5-iOS/Data/Sources/APIs/Camera/DataMapping/CameraRealEmojiPreSignedResponseDTO.swift
  14th-team5-iOS/Data/Sources/APIs/Camera/DataMapping/CameraTodayMissionResponseDTO.swift
  14th-team5-iOS/Data/Sources/APIs/Camera/DataMapping/CameraUpdateRealEmojiResponseDTO.swift
  14th-team5-iOS/Data/Sources/APIs/Camera/DataMapping/CreateEmojiImageReqeustDTO.swift
  14th-team5-iOS/Data/Sources/APIs/Camera/DataMapping/CreateFeedRequestDTO.swift
  14th-team5-iOS/Data/Sources/APIs/Camera/DataMapping/CreatePresignedURLReqeustDTO.swift
  14th-team5-iOS/Data/Sources/APIs/Camera/DataMapping/UpdateProfileImageRequestDTO.swift
  14th-team5-iOS/Data/Sources/APIs/Camera/DataMapping/UpdateRealEmojiImageRequestDTO.swift
  14th-team5-iOS/Data/Sources/APIs/Camera/Repository/CameraRepository.swift
  14th-team5-iOS/Data/Sources/APIs/Members/DataMapping/MembersProfileResponseDTO.swift
  14th-team5-iOS/Data/Sources/Trash/Camera/CameraAPI/CameraAPIWorker.swift
  14th-team5-iOS/Data/Sources/Trash/Camera/CameraAPI/CameraAPIs.swift
  14th-team5-iOS/Data/Sources/Trash/Camera/Repository/CameraRepository.swift
  14th-team5-iOS/Domain/Sources/Entities/Camera/CameraCreateRealEmojiEntity.swift
  14th-team5-iOS/Domain/Sources/Entities/Camera/CameraMissionFeedQuery.swift
  14th-team5-iOS/Domain/Sources/Entities/Camera/CameraPostEntity.swift
  14th-team5-iOS/Domain/Sources/Entities/Camera/CameraPreSignedEntity.swift
  14th-team5-iOS/Domain/Sources/Entities/Camera/CameraRealEmojiImageItemEntity.swift
  14th-team5-iOS/Domain/Sources/Entities/Camera/CameraRealEmojiItems.swift
  14th-team5-iOS/Domain/Sources/Entities/Camera/CameraRealEmojiPreSignedEntity.swift
  14th-team5-iOS/Domain/Sources/Entities/Camera/CameraTodayMssionEntity.swift
  14th-team5-iOS/Domain/Sources/Entities/Camera/CameraUpdateRealEmojiEntity.swift
  14th-team5-iOS/Domain/Sources/Entities/Camera/CreateEmojiImageRequest.swift
  14th-team5-iOS/Domain/Sources/Entities/Camera/CreateFeedQuery.swift
  14th-team5-iOS/Domain/Sources/Entities/Camera/CreateFeedRequest.swift
  14th-team5-iOS/Domain/Sources/Entities/Camera/CreatePresignedURLRequest.swift
  14th-team5-iOS/Domain/Sources/Entities/Camera/UpdateProfileImageRequest.swift
  14th-team5-iOS/Domain/Sources/Entities/Camera/UpdateRealEmojiImageRequest.swift
  14th-team5-iOS/Domain/Sources/Repositories/CameraRepository.swift
  14th-team5-iOS/Domain/Sources/Trash/Account/Parameters/CameraDisplayImageParameters.swift
  14th-team5-iOS/Domain/Sources/Trash/Camera/Parameters/CameraCreateRealEmojiParameters.swift
  14th-team5-iOS/Domain/Sources/Trash/Camera/Parameters/CameraRealEmojiParameters.swift
  14th-team5-iOS/Domain/Sources/Trash/Camera/Parameters/CameraUpdateRealEmojiParameters.swift
  14th-team5-iOS/Domain/Sources/Trash/Camera/UseCases/Mission/FetchCameraTodayMissionUseCase.swift
  14th-team5-iOS/Domain/Sources/Trash/Camera/UseCases/Profile/EditCameraProfileImageUseCase.swift
  14th-team5-iOS/Domain/Sources/Trash/Camera/UseCases/RealEmoji/FetchCameraRealEmojiListUseCase.swift
  14th-team5-iOS/Domain/Sources/Trash/Camera/UseCases/RealEmoji/FetchCameraRealEmojiUpdateUseCase.swift
  14th-team5-iOS/Domain/Sources/Trash/Camera/UseCases/RealEmoji/FetchCameraRealEmojiUploadUseCase.swift
  14th-team5-iOS/Domain/Sources/Trash/Camera/UseCases/RealEmoji/FetchCameraRealEmojiUseCase.swift
  14th-team5-iOS/Domain/Sources/UseCases/Camera/CreateCameraImageUseCase.swift
  14th-team5-iOS/Domain/Sources/UseCases/Camera/CreateCameraUseCase.swift
  14th-team5-iOS/Domain/Sources/UseCases/Camera/FetchCameraUploadImageUseCase.swift
Labels: 🦊 도현, 🛠️REACTOR

#709 refactor: 기존 MissionAPIWorker Network Module 리팩토링해요
  14th-team5-iOS/Data/Sources/Trash/Mission/MissionAPI/MissionAPIWorker.swift
  14th-team5-iOS/Data/Sources/Trash/Mission/MissionAPI/MissionAPIs.swift
  14th-team5-iOS/Data/Sources/Trash/Mission/Repository/MissionRepository.swift
  14th-team5-iOS/Domain/Sources/Entities/Mission/MissionContentEntity.swift
  14th-team5-iOS/Domain/Sources/Repositories/MissonRepository.swift
  14th-team5-iOS/Domain/Sources/Trash/Mission/Interfaces/MissionRepositoryProtocol.swift
  14th-team5-iOS/Domain/Sources/UseCases/Misson/CheckMissionAlertShowUseCase.swift
  14th-team5-iOS/Domain/Sources/UseCases/Misson/FetchMissionContentUseCase.swift
Labels: 🦊 도현, 🛠️REACTOR

#716 fix: PickRepository, ResignRepository 파일 및 폴더 생성
  14th-team5-iOS/App/Sources/Application/AppDelegate.swift
  14th-team5-iOS/App/Sources/Application/DIContainer/PickDICotainer.swift
  14th-team5-iOS/App/Sources/Application/DIContainer/ProfileDIContainer.swift
  14th-team5-iOS/App/Sources/Application/DIContainer/ResignDIContainer.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/BBNetworkInterceptor.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/Components/BBNetworkHeader.swift
  14th-team5-iOS/Data/Sources/APIs/Members/MembersAPIs.swift
  14th-team5-iOS/Data/Sources/Repositories/MembersRepository.swift
  14th-team5-iOS/Data/Sources/Repositories/PickRepository.swift
  14th-team5-iOS/Data/Sources/Repositories/ResignRepository.swift
  14th-team5-iOS/Domain/Sources/Repositories/MembersRepository.swift
  14th-team5-iOS/Domain/Sources/Repositories/PickRepository.swift
  14th-team5-iOS/Domain/Sources/Repositories/ResignRepository.swift
  14th-team5-iOS/Domain/Sources/UseCases/Members/CreateMembersPickUseCase.swift
  14th-team5-iOS/Domain/Sources/UseCases/Members/DeleteMembersUseCase.swift
Labels: ✨ FEATURE, 🦊 도현
