Repository depromeet/14th-team5-iOS, pull requests merged in 2024-04, with the labels that each got.

#462 feat: 오늘 생존신고하였는지 확인하는 기능 수정(#461)
  14th-team5-iOS/App/Sources/Presentation/Home/Dependency/HomeDIContainer.swift
  14th-team5-iOS/App/Sources/Presentation/Home/Reactor/HomeViewReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Home/ViewControllers/HomeViewController.swift
  14th-team5-iOS/App/Sources/Presentation/PostDetail/Dependency/PostListsDIContainer.swift
  14th-team5-iOS/Core/Sources/Extensions/UserDefaults+Ext.swift
  14th-team5-iOS/Data/Sources/Camera/CameraAPI/CameraAPIWorker.swift
  14th-team5-iOS/Data/Sources/Camera/DataMapping/CameraDisplayPostDTO.swift
  14th-team5-iOS/Data/Sources/Post/PostList/PostListAPI/PostListAPIWorker.swift
  14th-team5-iOS/Data/Sources/UserDefaults/PostUserDefaults.swift
  14th-team5-iOS/Domain/Sources/Post/Interfaces/UploadPostRepositoryProtocol.swift
  14th-team5-iOS/Domain/Sources/Post/UseCases/PostListUseCase.swift
Labels: ✨ FEATURE

#466 fix: base_ref release, develop 조건절 수정
  .github/workflows/swift.yml
Labels: ⚒️ SETTING, 🦊 도현

#468 fix: gihhub Action CI/CD 배포 Branch 전략 수정
  .github/workflows/swift.yml
Labels: ⚒️ SETTING

#471 feat: 재촉하기 네트워크 통신 로직 구현
  14th-team5-iOS/App/Project.swift
  14th-team5-iOS/Data/Sources/Pick/PickAPI/DataMapping/PickMemberListResponseDTO.swift
  14th-team5-iOS/Data/Sources/Pick/PickAPI/DataMapping/PickResponseDTO.swift
  14th-team5-iOS/Data/Sources/Pick/PickAPI/PickAPIWorker.swift
  14th-team5-iOS/Data/Sources/Pick/PickAPI/PickAPIs.swift
  14th-team5-iOS/Data/Sources/Pick/Repository/PickRepository.swift
  14th-team5-iOS/Domain/Sources/Pick/Entities/PickMemberListResponse.swift
  14th-team5-iOS/Domain/Sources/Pick/Entities/PickResponse.swift
  14th-team5-iOS/Domain/Sources/Pick/Interfaces/Repositories/PickRepositoryProtocol.swift
  14th-team5-iOS/Domain/Sources/Pick/UseCases/PickUseCase.swift
Labels: ✨ FEATURE, 🐼 건우

#479 feat: BibbiAlertBuilder, BibbiAlertViewController UI 및 기능 구현
  14th-team5-iOS/Core/Sources/Bibbi/BibbiAlertBuilder/BibbiAlertAction.swift
  14th-team5-iOS/Core/Sources/Bibbi/BibbiAlertBuilder/BibbiAlertBuilder.swift
  14th-team5-iOS/Core/Sources/Bibbi/BibbiAlertBuilder/BibbiAlertStyle.swift
  14th-team5-iOS/Core/Sources/Bibbi/BibbiAlertBuilder/BibbiAlertTitle.swift
  14th-team5-iOS/Core/Sources/Bibbi/BibbiAlertBuilder/BibbiAlertViewController.swift
  14th-team5-iOS/Core/Sources/Bibbi/BibbiButton/BibbiButton.swift
  14th-team5-iOS/Core/Sources/Bibbi/BibbiLabel/BibbiLabel.swift
  14th-team5-iOS/Core/Sources/Bibbi/BibbiNavigationBarView/BibbiNavigationBarView.swift
  14th-team5-iOS/Core/Sources/Bibbi/BibbiNavigationBarView/DelegateProxy/RxBibbiNavigationDelegateProxy.swift
  14th-team5-iOS/Core/Sources/Bibbi/BibbiSegmentedControl/BibbiSegmentedControl.swift
  14th-team5-iOS/Core/Sources/Bibbi/BibbiToastMessageView/BibbiToastMessageView.swift
  14th-team5-iOS/Core/Sources/Extensions/NSMutableAttributedString+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UIButton+Ext.swift
  14th-team5-iOS/Core/Sources/Extensions/UIImage+Ext.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/Character/ExhaustedBibbiGraphic.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/Character/ExhaustedBibbiGraphic.imageset/ExhaustedBibbiGraphic.svg
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/Character/MissionKeyGraphic.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/Character/MissionKeyGraphic.imageset/MissionKeyGraphic.svg
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/Character/TakeSurvivalGraphic.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/Character/TakeSurvivalGraphic.imageset/flagCamera.svg
  Bibbi.xcworkspace/xcshareddata/xcschemes/Bibbi-Workspace.xcscheme
Labels: ✨ FEATURE, 🐼 건우

#483 feat: ProfileView Mission Feed API 추가
  14th-team5-iOS/App/Sources/Presentation/Camera/Cell/DisplayEditCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Cell/CellReactor/ProfileFeedCellReactor.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Cell/ProfileFeedCollectionViewCell.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Cell/ProfileFeedDescrptionCell.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/ProfileViewController.swift
  14th-team5-iOS/App/Sources/Presentation/Profile/Reactor/ProfileViewReactor.swift
  14th-team5-iOS/Core/Sources/Bibbi/BibbiSegmentedControl/BibbiSegmentedControl.swift
  14th-team5-iOS/Data/Sources/Profile/DataMapping/ProfilePostDTO.swift
  14th-team5-iOS/Data/Sources/Profile/Repositories/ProfileViewRepository.swift
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/missionBadge.imageset/Contents.json
  14th-team5-iOS/DesignSystem/Resources/Assets.xcassets/icons/missionBadge.imageset/missionBadge.svg
  14th-team5-iOS/Domain/Sources/Profile/Entity/ProfilePostResponse.swift
  14th-team5-iOS/Domain/Sources/Profile/Parameters/ProfilePostParameter.swift
Labels: ✨ FEATURE, 🦊 도현
