Repository depromeet/14th-team5-iOS, pull requests merged in 2025-08, with the labels that each got.

#774 fix: MainViewController googleBannerView 제거
  14th-team5-iOS/Bibbi/Sources/Presentation/Home/ViewControllers/MainViewController.swift
Labels: 🦊 도현

#772 위젯이 안되는 현상을 수정해요
  14th-team5-iOS/Bibbi/Project.swift
  14th-team5-iOS/Bibbi/WidgetExtension/Sources/FamilyWidget/FamilyWidgetTimelineProvider.swift
  14th-team5-iOS/Bibbi/WidgetExtension/Sources/FamilyWidget/FamilyWidgetView.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBNetwork/Network/Components/BBNetworkHeader.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBStorages/KeychainWrapper/KeychainWrapper.swift
  14th-team5-iOS/Core/Sources/Bibbi/BBStorages/UserDefaultsWrapper/UserDefaultsWrapper.swift
  14th-team5-iOS/Core/Sources/Extensions/Bundle+Ext.swift
  14th-team5-iOS/Core/Sources/Trash/BBNetwork/API.swift
  14th-team5-iOS/Core/Sources/Trash/BBRx/Repositories/Token/TokenRepository.swift
  14th-team5-iOS/Data/Sources/APIs/Widget/WidgetAPIWorker.swift
  14th-team5-iOS/Data/Sources/APIs/Widget/WidgetAPIs.swift
  14th-team5-iOS/Data/Sources/Repositories/AppRepository.swift
  14th-team5-iOS/Data/Sources/Repositories/WidgetRepository.swift
  14th-team5-iOS/Data/Sources/Trash/Account/AccountRepository/AccountRepository.swift
  14th-team5-iOS/Domain/Sources/Repositories/WidgetRepository.swift
  14th-team5-iOS/Domain/Sources/UseCases/Widget/FetchRecentFamilyPostUseCase.swift
Labels: ✨ FEATURE

#776 fix: CameraDisplayViewController displayBannerView addsubView 메서드에 추가
  14th-team5-iOS/Bibbi/Project.swift
  14th-team5-iOS/Bibbi/Sources/Presentation/Camera/CameraDisplayViewController.swift
  14th-team5-iOS/Bibbi/Sources/Presentation/Camera/CameraViewController.swift
  14th-team5-iOS/Core/Sources/Extensions/Bundle+Ext.swift
  14th-team5-iOS/Core/Sources/Trash/BBNetwork/API.swift
  14th-team5-iOS/Data/Sources/Repositories/AppRepository.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 🐞 BUG, 🦊 도현, HOTFIX
